Repository wpeverest/user-registration, pull requests merged in 2018-02, with the labels that each got.

#22 Redirect to custom page via email
  includes/admin/settings/emails/class-ur-settings-email-confirmation.php
  includes/class-ur-email-confirmation.php
  templates/form-registration.php
  templates/myaccount/form-login.php
Labels: enhancement

#23 Update postmeta instead of usermeta
  includes/admin/class-ur-admin-profile.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-template.php
Labels: Impact: High, enhancement

#26 Refactor how the checkboxes are stored in db
  includes/admin/class-ur-admin-profile.php
  includes/class-ur-form-handler.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-template.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Needs Tests, enhancement

#28 Refactor checkbox and optimize query
  includes/functions-ur-update.php
Labels: Focus: Performance, Status: Needs Review, Status: Needs Tests

#29 Refactor update and delete usermeta in single function
  includes/class-ur-install.php
  includes/functions-ur-update.php
Labels: Focus: Performance, Impact: Mind blown

#24 Refactor the entire process of user data store
  Gruntfile.js
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/js/frontend/user-registration.min.js
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-profile.php
  includes/class-ur-form-handler.php
  includes/class-ur-install.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  includes/functions-ur-update.php
  languages/user-registration.pot
  package-lock.json
  readme.txt
  templates/myaccount/form-edit-profile.php
Labels: Focus: Performance, Impact: High, Release: Minor, Status: Approved

#31 Fix - list table autoload call on demand to reduce memory consumption
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-registrations-table-list.php
  uninstall.php
Labels: Focus: Performance

#32 Privacy policy display from form
  includes/admin/class-ur-admin-profile.php
Labels: Status: Approved, bug
