Repository wpeverest/user-registration, pull requests merged in 2018-05, with the labels that each got.

#54 Feature/custom reset password
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/emails/class-ur-settings-reset-password-email.php
  includes/class-ur-emailer.php
  includes/functions-ur-account.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  templates/myaccount/lost-password-confirmation.php
Labels: Status: Needs Tests, enhancement

#53 Refactor/prefix
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-profile.php
  includes/admin/views/html-admin-page-forms.php
  includes/class-ur-ajax.php
  includes/class-ur-emailer.php
  includes/class-ur-form-handler.php
  includes/class-ur-install.php
  includes/form/class-ur-description.php
  includes/form/class-ur-display-name.php
  includes/form/class-ur-first-name.php
  includes/form/class-ur-last-name.php
  includes/form/class-ur-nickname.php
  includes/form/class-ur-user-login.php
  includes/form/class-ur-user-pass.php
  includes/form/views/admin/admin-description.php
  includes/form/views/admin/admin-display-name.php
  includes/form/views/admin/admin-first-name.php
  includes/form/views/admin/admin-last-name.php
  includes/form/views/admin/admin-nickname.php
  includes/form/views/admin/admin-user-login.php
  includes/form/views/admin/admin-user-pass.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  includes/functions-ur-update.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  user-registration.php
Labels: Impact: High, Status: Needs Tests, Type: Refactor, enhancement

#49 Remove js code and redirect using template_redirect hook
  includes/functions-ur-template.php
  includes/shortcodes/class-ur-shortcode-login.php
Labels: Status: Needs Review, Status: Needs Tests

#52 Fixes
  includes/admin/settings/emails/class-ur-settings-awaiting-admin-approval-email.php
  includes/admin/settings/emails/class-ur-settings-email-confirmation.php
  includes/admin/settings/emails/class-ur-settings-registration-approved-email.php
  includes/admin/settings/emails/class-ur-settings-registration-denied-email.php
  includes/admin/settings/emails/class-ur-settings-registration-pending-email.php
  includes/admin/settings/emails/class-ur-settings-successfully-registered-email.php
  includes/class-ur-email-confirmation.php
  includes/class-ur-emailer.php
Labels: Impact: Low

#55 enhance "user_registration_check_token_complete"
  includes/class-ur-email-confirmation.php
Labels: Status: Needs Tests

#59 Feature/export erase
  includes/admin/functions-ur-admin.php
Labels: Status: In Progress, Status: Needs Review, Status: Needs Tests

#58 Fixes and minor changes
  includes/admin/settings/emails/class-ur-settings-admin-email.php
  includes/admin/settings/emails/class-ur-settings-awaiting-admin-approval-email.php
  includes/admin/settings/emails/class-ur-settings-email-confirmation.php
  includes/admin/settings/emails/class-ur-settings-registration-approved-email.php
  includes/admin/settings/emails/class-ur-settings-registration-denied-email.php
  includes/admin/settings/emails/class-ur-settings-registration-pending-email.php
  includes/admin/settings/emails/class-ur-settings-reset-password-email.php
  includes/admin/settings/emails/class-ur-settings-successfully-registered-email.php
  includes/form/class-ur-country.php
Labels: Status: In Progress, Status: Needs Tests
