Repository wpeverest/user-registration, pull requests merged in 2019-09, with the labels that each got.

#152 Feature - Live new user registration notice and badge
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/js/admin/live-user-notice.js
  assets/js/admin/live-user-notice.min.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin.php
Labels: Status: Approved, enhancement

#160 Enhancement/import export form json
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-import-export-forms.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/class-ur-admin.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-import-export.php
  includes/admin/views/html-admin-page-import-export-forms.php
  includes/class-ur-ajax.php
Labels: Status: Approved, enhancement

#165 UI change
  assets/css/_button.scss
  assets/css/_colors.scss
  assets/css/_fonts.scss
  assets/css/_variables.scss
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/perfect-scrollbar/perfect-scrollbar.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/fonts/UserRegistration.eot
  assets/fonts/UserRegistration.svg
  assets/fonts/UserRegistration.ttf
  assets/fonts/UserRegistration.woff
  assets/images/logo.svg
  assets/js/admin/admin.js
  assets/js/admin/admin.min.js
  assets/js/perfect-scrollbar/perfect-scrollbar.js
  assets/js/perfect-scrollbar/perfect-scrollbar.min.js
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/functions-ur-admin.php
  includes/admin/views/html-admin-page-forms.php
  includes/class-ur-ajax.php
  includes/class-ur-preview.php
  includes/class-ur-shortcodes.php
  includes/form/class-ur-form-field-checkbox.php
  includes/form/class-ur-form-field-country.php
  includes/form/class-ur-form-field-date.php
  includes/form/class-ur-form-field-description.php
  includes/form/class-ur-form-field-display-name.php
  includes/form/class-ur-form-field-email.php
  includes/form/class-ur-form-field-first-name.php
  includes/form/class-ur-form-field-last-name.php
  includes/form/class-ur-form-field-nickname.php
  includes/form/class-ur-form-field-number.php
  includes/form/class-ur-form-field-password.php
  includes/form/class-ur-form-field-privacy-policy.php
  includes/form/class-ur-form-field-radio.php
  includes/form/class-ur-form-field-select.php
  includes/form/class-ur-form-field-text.php
  includes/form/class-ur-form-field-textarea.php
  includes/form/class-ur-form-field-user-confirm-email.php
  includes/form/class-ur-form-field-user-confirm-password.php
  includes/form/class-ur-form-field-user-email.php
  includes/form/class-ur-form-field-user-login.php
  includes/form/class-ur-form-field-user-pass.php
  includes/form/class-ur-form-field-user-url.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  languages/user-registration.pot
  templates/form-registration.php
Labels: Status: Needs Docs, enhancement

#167 Fix/switch focusout code from jquery validate to user registration
  assets/js/frontend/jquery.validate.js
  assets/js/frontend/user-registration.js
Labels: Status: Approved

#166 Fix - Password validation message
  includes/class-ur-emailer.php
  includes/frontend/class-ur-frontend-form-handler.php
Labels: enhancement
