Repository wpeverest/user-registration, pull requests merged in 2019-12, with the labels that each got.

#183 Correcting misbehaving data attrib and value fields for checkbox
  includes/functions-ur-template.php
Labels: Status: Needs Review, bug

#178 Redirect url after logout
  includes/functions-ur-template.php
Labels: Status: Needs Docs, enhancement

#179 Removed notice from form builder
  includes/admin/class-ur-admin-notices.php
Labels: bug

#182 Enhance/password field eye icon
  assets/css/user-registration.css
  assets/js/frontend/password-strength-meter.js
  assets/js/frontend/user-registration.js
  includes/admin/settings/class-ur-settings-general.php
  includes/functions-ur-template.php
Labels: Status: Needs Docs, Status: Ready to Merge, enhancement

#185 Enhance/phone field
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.scss
  assets/js/frontend/my-account.js
  assets/js/frontend/my-account.min.js
  assets/js/frontend/user-registration.js
  assets/js/frontend/user-registration.min.js
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-frontend-scripts.php
  templates/myaccount/form-edit-profile.php
  wpml-config.xml
Labels: Status: Ready to Merge, enhancement

#187 Enhance/registered user source
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin.php
Labels: Status: Ready to Merge, enhancement
