Repository wpeverest/user-registration, pull requests merged in 2019-06, with the labels that each got.

#143 Fix - Invite code sub menu
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
Labels: enhancement

#147 Lost password Email headers issue
  includes/class-ur-emailer.php
Labels: bug

#144 Fix: Json_decode error on user profile.
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: Status: Needs Review, bug

#148 Fix/admin register user
  includes/class-ur-ajax.php
Labels: enhancement

#140 Two column login reg page
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration-smallscreen.scss
  assets/css/user-registration.css
  assets/css/user-registration.scss
  includes/shortcodes/class-ur-shortcode-my-account.php
  languages/user-registration.pot
  templates/form-login-registration.php
Labels: Status: Needs Review, enhancement
