Repository wpeverest/user-registration, pull requests merged in 2019-05, with the labels that each got.

#125 Gravatar message hide when custom picture selected
  templates/myaccount/form-edit-profile.php
Labels: Accessibility, Impact: Low

#123 Form preview
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-registrations-table-list.php
  includes/admin/views/html-admin-page-forms.php
  includes/class-ur-preview.php
  user-registration.php
Labels: Status: Needs Review

#131 Redirect to dashboard on prevent core login is active and is user adm…
  includes/class-ur-form-handler.php
Labels: Status: Needs Review

#97 Form wise redirection
  assets/js/frontend/user-registration.js
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-frontend-scripts.php
  includes/class-ur-install.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  includes/functions-ur-update.php
  templates/form-registration.php
Labels: Status: Needs Tests, Type: Refactor, enhancement

#132 Enhancement - Edit profile dashboard
  assets/css/_button.scss
  assets/css/_colors.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/my-account-layout.scss
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration-smallscreen.scss
  assets/css/user-registration.css
  assets/css/user-registration.scss
  includes/shortcodes/class-ur-shortcode-my-account.php
  package-lock.json
  readme.txt
  templates/myaccount/dashboard.php
  templates/myaccount/form-edit-password.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Needs Review, enhancement

#122 Fix - Field structure in edit profile. Closes #108
  assets/css/_button.scss
  assets/css/_colors.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/my-account-layout.scss
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration-smallscreen.scss
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/js/frontend/user-registration.js
  assets/js/frontend/user-registration.min.js
  includes/class-ur-frontend-scripts.php
  includes/functions-ur-core.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  readme.txt
  templates/myaccount/dashboard.php
  templates/myaccount/form-edit-password.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Needs Review

#133 Enhancement - Sub-navigation design on setting page
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  includes/admin/settings/class-ur-settings-page.php
  includes/admin/views/html-admin-page-addons.php
Labels: Status: Needs Review, Type: Enhancement

#134 Added Email confirmation field. Closes #98
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-frontend-scripts.php
  includes/form/class-ur-form-field-user-confirm-email.php
  includes/form/settings/class-ur-setting-user_confirm_email.php
  includes/form/views/admin/admin-user-confirm-email.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
Labels: Status: Needs Review, enhancement

#120 Max length input fields
  includes/abstracts/abstract-ur-field-settings.php
  includes/abstracts/abstract-ur-form-field.php
  includes/form/settings/class-ur-setting-number.php
  includes/functions-ur-template.php
Labels: Status: Needs Review

#135 Fix - Lost Password Endpoint conflict with WooCommerce
  includes/admin/class-ur-admin-menus.php
  includes/class-ur-query.php
  includes/functions-ur-core.php
  includes/shortcodes/class-ur-shortcode-login.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: Impact: Medium, Status: Needs Review, bug

#137 Tweak - change edit registration link in form preview
  includes/class-ur-preview.php
Labels: Status: Ready to Merge, enhancement

#136 Fix/undefined error registration ajax
  includes/class-ur-ajax.php
Labels: Status: Needs Review, bug

#138 Tweak - Conditional logic option design
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
Labels: enhancement

#145 Contributing templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/-----security-issue.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Enhancement.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Support.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Impact: Medium, Status: Approved, enhancement
