Repository wpeverest/user-registration, pull requests merged in 2019-08, with the labels that each got.

#159 Form end hook
  templates/form-registration.php
Labels: enhancement

#157 Fix/pw strength error msg
  assets/js/frontend/jquery.validate.js
  assets/js/frontend/password-strength-meter.js
  assets/js/frontend/user-registration.js
Labels: Status: Ready to Merge, bug

#162 Profile details field hook
  templates/myaccount/form-edit-profile.php
Labels: bug

#161 Add - Accept redirect_to get parameter in login page
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: Feature Request

#154 Feature - Fullscreen builder mode
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/js/admin/admin.js
  assets/js/admin/admin.min.js
  assets/js/frontend/jquery.min.js
  assets/js/frontend/password-strength-meter.min.js
  assets/js/frontend/user-registration.min.js
  includes/admin/views/html-admin-page-forms.php
  languages/user-registration.pot
Labels: Status: Needs Review, enhancement

#158 enhancement/profile changed email
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/emails/class-ur-settings-profile-details-changed-email.php
  includes/class-ur-emailer.php
  includes/class-ur-form-handler.php
Labels: Status: Ready to Merge, enhancement

#163 Fix - Email format issue
  includes/admin/settings/emails/class-ur-settings-admin-email.php
  includes/admin/settings/emails/class-ur-settings-awaiting-admin-approval-email.php
  includes/admin/settings/emails/class-ur-settings-email-confirmation.php
  includes/admin/settings/emails/class-ur-settings-registration-approved-email.php
  includes/admin/settings/emails/class-ur-settings-registration-denied-email.php
  includes/admin/settings/emails/class-ur-settings-registration-pending-email.php
  includes/admin/settings/emails/class-ur-settings-reset-password-email.php
  includes/admin/settings/emails/class-ur-settings-successfully-registered-email.php
Labels: Accessibility

#164 Tweak - Template file update to locate add-ons file
  includes/functions-ur-core.php
Labels: enhancement
