Repository wpeverest/user-registration, pull requests merged in 2020-03, with the labels that each got.

#206 Refactor - Sass variables
  assets/css/_button.scss
  assets/css/_colors.scss
  assets/css/_tables.scss
  assets/css/_variables.scss
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/my-account-layout.scss
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration-smallscreen.scss
  assets/css/user-registration.css
  assets/css/user-registration.scss
Labels: Status: Needs Review, enhancement

#213 Refactor - Sass code
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  includes/admin/views/html-admin-page-addons.php
Labels: Status: Needs Review, enhancement

#198 Fix: WPML on multiple choice options
  includes/abstracts/abstract-ur-form-field.php
Labels: Status: Needs Review, bug

#210 Fix- Enqueue password strength
  assets/js/frontend/password-strength-meter.js
  assets/js/frontend/user-registration.js
  includes/shortcodes/class-ur-shortcode-my-account.php
  templates/myaccount/form-edit-password.php
Labels: Status: Needs Review

#209 Enhance - Custom class for submit button
  includes/functions-ur-core.php
  templates/form-registration.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Needs Review, enhancement

#208 Enhance - Core Login disable feature QoL changes
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-general.php
  includes/frontend/class-ur-frontend.php
Labels: Status: Needs Design, Status: Needs Docs, Status: Needs Review

#211 Enhance/search fields
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/images/not-found.png
  assets/js/admin/admin.js
  includes/admin/views/html-admin-page-forms.php
  includes/functions-ur-template.php
Labels: Status: Needs Review, enhancement
