Repository wpeverest/user-registration, pull requests merged in 2020-11, with the labels that each got.

#285 Fix - Conditional Logic in my account
  templates/myaccount/form-edit-profile.php
Labels: Status: Approved, Status: Ready to Merge, bug

#284 Fix - Conditional Logic and Required fields conflict
  includes/frontend/class-ur-frontend-form-handler.php
Labels: Status: Approved, Status: Ready to Merge, bug

#283 Dev - Zapier addon compatibility.
  includes/functions-ur-core.php
Labels: Status: Approved, Status: Needs Tests, Status: Ready to Merge

#282 Tweak - Hide unrelated admin notices from settings page
  includes/admin/class-ur-admin-notices.php
  includes/admin/class-ur-admin-user-list-manager.php
Labels: Status: Approved, Status: Ready to Merge, enhancement

#280 Tweak - Number field validation message override and translatable
  assets/js/frontend/user-registration.js
  includes/class-ur-frontend-scripts.php
Labels: Status: Approved, Status: Ready to Merge, enhancement

#279 Enhance - Max upload size and valid file type settings value save and retrieve
  assets/js/admin/admin.js
  assets/js/admin/plugins.js
  includes/abstracts/abstract-ur-field-settings.php
  includes/abstracts/abstract-ur-form-field.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Approved, Status: Ready to Merge, enhancement

#281 Enhance- Re-initialize form after full page load
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  includes/class-ur-frontend-scripts.php
Labels: Status: Approved, Status: Ready to Merge, enhancement

#276 Feature - Email content override for Email Templates addon.
  assets/css/_forms.scss
  assets/css/_overlay.scss
  assets/css/admin.scss
  assets/css/components/_button.scss
  assets/css/components/_list-group.scss
  assets/css/templates/_template-setup.scss
  assets/css/variables/_colors.scss
  assets/js/admin/admin.js
  assets/js/ur-components/ur-components.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/functions-ur-admin.php
  includes/class-ur-emailer.php
  includes/class-ur-user-approval.php
  includes/functions-ur-core.php
Labels: Status: Approved, Status: Ready to Merge, Type: Feature Plugin

#275 Fix - Conditional logic not working in WooCommerce checkout page
  includes/functions-ur-template.php
Labels: Status: Approved, Status: Ready to Merge, bug

#289 Refactor - Grids and containers sass files
  assets/css/_containers.scss
  assets/css/_grid.scss
  assets/css/_grids.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/variables/_grids.scss
Labels: enhancement

#294 Fix - Hide/Show password conflict with form re-initialization
  assets/js/frontend/user-registration.js
Labels: Status: Approved, bug

#293 Fix - Export users fails due to form name with dash.
  includes/admin/class-ur-admin-export-users.php
Labels: Status: Approved, Status: Tested, bug

#291 Fix - Fatal error while resend verification.
  includes/class-ur-email-confirmation.php
  templates/myaccount/form-login.php
Labels: Status: Approved, Status: Tested, bug

#290 Fix- Missing attachment for single file upload due to form-filler
  assets/js/frontend/user-registration.js
Labels: Status: Approved, bug

#295 Fix - Scroll to the first error message on form submit
  assets/js/frontend/user-registration.js
Labels: Status: Needs Tests, bug
