Repository wpeverest/user-registration, pull requests merged in 2020-04, with the labels that each got.

#223 Fix - Form field validation for missing required fields
  includes/frontend/class-ur-frontend-form-handler.php
  templates/myaccount/form-edit-password.php
Labels: Status: Needs Tests, bug

#221 Enhance - Registered At column to display registered log.
  includes/admin/class-ur-admin-user-list-manager.php
Labels: Status: Needs Tests, enhancement

#220 Fix - User approval status.
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin-user-manager.php
  includes/class-ur-email-confirmation.php
  includes/class-ur-user-approval.php
Labels: Status: Needs Review, Status: Needs Tests, bug

#212 Fix/date picker
  assets/js/admin/admin.js
  assets/js/admin/admin.min.js
  assets/js/frontend/user-registration.js
  assets/js/frontend/user-registration.min.js
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-profile.php
  includes/functions-ur-template.php
Labels: Status: Needs Review, bug

#218 Fix - Section Division function now correctly redistributes columns
  assets/js/admin/admin.js
Labels: Status: Needs Review, bug

#217 Enhance - Popup field for deletion.
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-assets.php
Labels: Status: Needs Review, enhancement

#216 Enhance - now allows clicking out of form name edit inputbox
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-menus.php
Labels: Status: Needs Review, enhancement

#222 Fix - Elementor pro conflict with validation errors.
  assets/js/frontend/user-registration.js
Labels: Impact: High, Needs Extensive Test, bug
