Repository wpeverest/user-registration, pull requests merged in 2020-05, with the labels that each got.

#224 Enhance - Max uploadable file number setting.
  assets/js/admin/admin.js
  includes/abstracts/abstract-ur-form-field.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Needs Tests, enhancement

#225 Enhance - move custom class attrib to the wrapper container instead o…
  includes/frontend/class-ur-frontend.php
  templates/form-registration.php
Labels: Impact: Medium, Status: Needs Review, Type: Enhancement

#226 Dev - MailChimp add-on compatibility changes.
  includes/admin/class-ur-admin-profile.php
  includes/functions-ur-core.php
Labels: Status: Needs Review, enhancement

#229 Fix - Invalid invite code not validate and required sign not showing.
  assets/js/frontend/user-registration.js
  includes/abstracts/abstract-ur-form-field.php
  includes/frontend/class-ur-frontend-form-handler.php
Labels: Status: Needs Review, Type: Bug
