Repository wpeverest/user-registration, pull requests merged in 2020-07, with the labels that each got.

#230 Fix - Date field value disappearing from the Profile Details section
  assets/js/frontend/my-account.js
  includes/functions-ur-template.php
Labels: Status: Needs Review, Status: Needs Tests, bug

#234 Fix - User approval status change and filter.
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin-user-manager.php
Labels: Status: Needs Tests, bug

#236 Feature - Ajax form submission on edit profile
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/js/frontend/my-account.js
  assets/js/frontend/user-registration.js
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-ajax.php
  includes/class-ur-emailer.php
  includes/class-ur-form-handler.php
  includes/class-ur-frontend-scripts.php
  includes/functions-ur-template.php
  package-lock.json
  package.json
  templates/myaccount/form-edit-profile.php
Labels: Impact: High

#237 Enhance - Logic map implemented
  assets/css/_forms.scss
  assets/css/_spacing.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/components/_badge.scss
  assets/css/components/_button.scss
  assets/css/components/_card.scss
  assets/css/components/_list-group.scss
  assets/css/components/_modal.scss
  assets/css/dashboard.scss
  assets/css/layout/_header.scss
  assets/css/review.scss
  assets/css/snackbar/snackbar.css
  assets/css/snackbar/snackbar.scss
  assets/css/ur-snackbar/ur-snackbar.css
  assets/css/ur-snackbar/ur-snackbar.scss
  assets/css/user-registration.scss
  assets/js/admin/admin.js
  assets/js/snackbar/snackbar.js
  assets/js/ur-snackbar/ur-snackbar.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/views/html-admin-page-forms.php
  includes/functions-ur-core.php
  templates/form-registration.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Needs Review, Status: Needs Tests, enhancement

#232 Fix - My account shortocde with Elementor
  CHANGELOG.txt
  includes/class-ur-shortcodes.php
  includes/functions-ur-template.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  readme.txt
Labels: Status: Needs Review, Status: Needs Tests, bug

#239 Addon - User-Registration-Stripe
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/js/frontend/user-registration.js
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-profile.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-template.php
Labels: Feature Request

#238 Feature - Access rules implemented
  assets/css/_fonts.scss
  assets/css/_forms.scss
  assets/css/_grid.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/components/_button.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/layout/_header.scss
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/js/ur-components/ur-components.js
  includes/admin/views/html-admin-page-forms.php
Labels: Feature Request, Status: Needs Docs, Status: Needs Review, Status: Needs Tests
