Repository wpeverest/user-registration, pull requests merged in 2020-09, with the labels that each got.

#254 Fix - My account endpoint URLs on the home page.
  includes/functions-ur-account.php
  includes/functions-ur-page.php
Labels: Status: Approved, Status: Ready to Merge, bug

#256 Dev - Deprecate Everest Form Hook and introduce new hook instead.
  includes/class-ur-emailer.php
  includes/functions-ur-deprecated.php
  includes/functions-ur-template.php
Labels: Status: Approved, Status: Ready to Merge

#258 Fix - Disabled submit button on ReCaptcha fail
  assets/js/frontend/user-registration.js
Labels: Status: Approved, Status: Ready to Merge, bug

#259 Fix - Unselect All countries option in Country field
  assets/js/admin/admin.js
Labels: Status: Approved, Status: Ready to Merge, bug

#260 Enhance - Filter Users with approval status and specific UR forms.
  includes/admin/class-ur-admin-user-list-manager.php
Labels: Status: Approved, Status: Ready to Merge, enhancement

#263 Fix - Ignore missing field validation based on field visibility settings
  includes/frontend/class-ur-frontend-form-handler.php
Labels: Status: Approved, Status: Ready to Merge, bug

#267 Fix - Date Field value disappears on user update by admin and woocommerce compatibility
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-profile.php
Labels: Status: Approved, Status: Ready to Merge, bug

#268 Tweak - Delete UR data on uninstall
  uninstall.php
Labels: Status: Approved, Status: Ready to Merge, bug

#265 Dev-Change date() to date_i18n() function and Timezone Compatibility
  includes/abstracts/abstract-ur-form-field.php
  includes/abstracts/abstract-ur-log-handler.php
  includes/admin/class-ur-admin-profile.php
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/functions-ur-admin.php
  includes/form/settings/class-ur-setting-date.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-template.php
Labels: Status: Approved, enhancement

#261 Tweak - Choice field option value change and update
  assets/js/admin/admin.js
  includes/form/views/admin/admin-radio.php
  includes/functions-ur-template.php
Labels: Status: Approved, Status: Ready to Merge, bug

#262 Fix - Feature to Import/Export/Duplicate form not working
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-import-export-forms.php
  includes/admin/class-ur-admin-menus.php
  includes/class-ur-form-handler.php
Labels: Status: Approved, Status: Ready to Merge, bug

#270 Dev - Replaced Deprecated function with new one
  assets/js/frontend/password-strength-meter.js
  assets/js/frontend/user-registration.js
Labels: Status: Approved, Status: Ready to Merge, bug

#266 Enhance - Add placeholder option in the Date field
  includes/form/views/admin/admin-date.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: Status: Approved, Status: Ready to Merge, enhancement

#272 Fix - Enable/Disable option of conditional logic not working in wp5.5
  templates/form-registration.php
Labels: Status: Approved, bug
