Repository wpeverest/user-registration, pull requests merged in 2020-10, with the labels that each got.

#273 Fix - Send an email after payment validation
  includes/frontend/class-ur-frontend-form-handler.php
Labels: Status: Approved, Status: Ready to Merge, bug

#175 Hide signup link on login form if user registration is not open
  templates/myaccount/form-login.php
Labels: Status: Approved, Status: Ready to Merge

#274 Fix - Number field min/max options
  assets/js/admin/admin.js
  includes/abstracts/abstract-ur-form-field.php
  includes/functions-ur-template.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Approved, Status: Ready to Merge, bug

#278 Tweak - Design changes in file upload of setting page
  assets/css/_forms.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/views/html-admin-page-export-users.php
  includes/admin/views/html-admin-page-import-export-forms.php
Labels: Status: Approved, Status: Ready to Merge, enhancement
