Repository wpeverest/user-registration, pull requests merged in 2020-08, with the labels that each got.

#247 Refactor - SASS files
  assets/css/_display.scss
  assets/css/_grid.scss
  assets/css/_grids.scss
  assets/css/_spacing.scss
  assets/css/activation.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/components/_card.scss
  assets/css/components/_modal.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/css/mixins/_breakpoints.scss
  assets/css/mixins/_grids.scss
  assets/css/mixins/_mixins.scss
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/my-account-layout.scss
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration-smallscreen.scss
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/css/variables/_colors.scss
  assets/css/variables/_grids.scss
  assets/css/variables/_variables.scss
  includes/admin/class-ur-admin-menus.php
  includes/admin/views/html-admin-page-forms.php
Labels: Status: Needs Review, enhancement

#244 Enhance - Option to disable logout confirmation
  includes/admin/settings/class-ur-settings-general.php
  includes/functions-ur-page.php
Labels: Status: Needs Review, Status: Needs Tests, enhancement

#246 Fix - Reset password error for other plugins registered users
  includes/admin/class-ur-admin-user-manager.php
  includes/class-ur-user-approval.php
Labels: Status: Needs Tests, bug

#250 Enhance - Copy icon on shortcode column in registration forms list table
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/ur-copy.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-registrations-table-list.php
  package-lock.json
Labels: Status: Needs Tests, enhancement

#243 Fix - Required option and Hide Label option conflict
  assets/js/admin/admin.js
Labels: Status: Needs Review, bug

#251 Fix - Cannot auto-scroll while dragging fields in the form builder
  assets/js/admin/admin.js
Labels: Status: Needs Review, Status: Needs Tests, bug

#249 Enhance - Introduce tooltips in Form Builder
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.js
  includes/abstracts/abstract-ur-field-settings.php
  includes/abstracts/abstract-ur-form-field.php
  includes/form/settings/class-ur-setting-checkbox.php
  includes/form/settings/class-ur-setting-country.php
  includes/form/settings/class-ur-setting-date.php
  includes/form/settings/class-ur-setting-description.php
  includes/form/settings/class-ur-setting-display_name.php
  includes/form/settings/class-ur-setting-email.php
  includes/form/settings/class-ur-setting-first_name.php
  includes/form/settings/class-ur-setting-last_name.php
  includes/form/settings/class-ur-setting-nickname.php
  includes/form/settings/class-ur-setting-number.php
  includes/form/settings/class-ur-setting-password.php
  includes/form/settings/class-ur-setting-radio.php
  includes/form/settings/class-ur-setting-select.php
  includes/form/settings/class-ur-setting-text.php
  includes/form/settings/class-ur-setting-textarea.php
  includes/form/settings/class-ur-setting-user_confirm_email.php
  includes/form/settings/class-ur-setting-user_confirm_password.php
  includes/form/settings/class-ur-setting-user_email.php
  includes/form/settings/class-ur-setting-user_login.php
  includes/form/settings/class-ur-setting-user_pass.php
  includes/form/settings/class-ur-setting-user_url.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: Status: Needs Review, enhancement

#245 Enhance - Login form customization
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-form-handler.php
  templates/myaccount/form-login.php
  wpml-config.xml
Labels: Status: Needs Review, Status: Needs Tests, enhancement

#253 Fix - ReCaptcha script loads in lost password page
  includes/shortcodes/class-ur-shortcode-login.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: Status: Needs Tests, bug

#257 Dev - User registration fields sync with woocommerce
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: Needs Extensive Test, bug
