Repository wpeverest/user-registration, pull requests merged in 2021-04, with the labels that each got.

#316 Fix - Disable logout confirmation issue with logout endpoint menu
  includes/functions-ur-page.php
Labels: Status: Needs Review, Status: Needs Tests, bug

#317 Enhance - Password strength meter in reset
  assets/js/frontend/password-strength-meter.js
  includes/functions-ur-page.php
  templates/myaccount/form-reset-password.php
Labels: Status: Needs Review, Status: Needs Tests, enhancement

#319 Fix - Reset password button not working
  assets/js/frontend/user-registration-form-validator.js
Labels: Status: Needs Tests, bug

#321 Fix - Hide label in edit profile
  templates/myaccount/form-edit-profile.php
Labels: Status: Approved, Status: Ready to Merge, Status: Tested, bug

#315 Enhance - Disallow special characters in username field
  assets/js/frontend/user-registration-form-validator.js
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-frontend-scripts.php
  includes/form/settings/class-ur-setting-user_login.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: Status: Needs Review, Status: Needs Tests, enhancement

#322 Addon - Frontend listing
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/mixins/_mixins.scss
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/variables/_colors.scss
  includes/admin/class-ur-admin-assets.php
  includes/functions-ur-core.php
Labels: Status: Approved, Status: Ready to Merge, Status: Tested, Type: Feature Plugin

#324 Enhance - Review notice content and design
  assets/css/review.css
  assets/css/review.scss
  assets/images/UR-Logo.png
  includes/admin/class-ur-admin.php
Labels: Status: Needs Review, Status: Needs Tests, enhancement

#320 Dev - iDEAL payment compatibility
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/js/admin/admin.js
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-profile.php
  includes/frontend/class-ur-frontend-form-handler.php
Labels: Status: Needs Review, Status: Needs Tests

#327 Fix- Reset password currently accepts same old password
  includes/class-ur-form-handler.php
  templates/myaccount/form-reset-password.php
Labels: Impact: Low, Status: Approved, Status: Ready to Merge, bug

#325 Tweak - Global function for smart tag name_value parser
  includes/class-ur-emailer.php
  includes/functions-ur-core.php
Labels: Status: Approved, Status: Ready to Merge, Status: Tested, bug

#323 Feature - Disable profile picture in my account
  assets/js/frontend/user-registration.js
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  templates/myaccount/dashboard.php
  templates/myaccount/form-edit-profile.php
Labels: Feature Request, Status: Approved, Status: Ready to Merge, Status: Tested

#328 Feature - Login Form Using Ajax
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/select2.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/js/frontend/ur-login.js
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/class-ur-frontend-scripts.php
  includes/class-ur-shortcodes.php
  templates/myaccount/form-login.php
Labels: Impact: Medium, Status: Approved, Status: Ready to Merge, Status: Tested

#326 Enhance - Pending approval banner
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin.php
  includes/admin/functions-ur-admin.php
  package-lock.json
Labels: Impact: Low, Status: Needs Tests, enhancement

#330 Fix - Disable email confirmation login using social connect
  includes/class-ur-email-confirmation.php
  includes/class-ur-user-approval.php
Labels: Impact: Low, Status: Needs Review, Status: Needs Tests, bug
