Repository wpeverest/user-registration, pull requests merged in 2021-09, with the labels that each got.

#363 Security - Authenticated xss issue
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
Labels: bug, Approved, Ready to Merge, Tested

#362 Fix - Profile picture field visible in edit-profile when gutenberg myaccount shortcode used
  assets/js/admin/gutenberg/form-block.build.js
  assets/js/admin/gutenberg/form-block.js
  includes/class-ur-form-block.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: bug, Impact: Medium, Approved, Ready to Merge, Tested

#359 Fix - Prevent core login in gutenberg login form
  includes/frontend/class-ur-frontend.php
Labels: bug, Impact: Medium, Approved, Ready to Merge, Tested

#366 Enhance - User creation capability check while registering users
  includes/class-ur-ajax.php
Labels: enhancement, Impact: Medium, Ready to Merge, Tested

#364 Enhancement - Time Picker Field
  includes/abstracts/abstract-ur-form-field.php
  includes/functions-ur-template.php
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Needs Review, Needs Tests

#365 Feature - Multiple choice Field
  assets/css/_fonts.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/fonts/UserRegistration.eot
  assets/fonts/UserRegistration.svg
  assets/fonts/UserRegistration.ttf
  assets/fonts/UserRegistration.woff
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration-form-validator.js
  assets/js/frontend/user-registration.js
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-profile.php
  includes/functions-ur-core.php
  package-lock.json
Labels: Approved, Feature Request, Merged, Tested
