Repository wpeverest/user-registration, pull requests merged in 2021-12, with the labels that each got.

#372 Addon - User Registration Pro
  .github/workflows/sync-file-list.yml
  .github/workflows/sync.yml
  assets/css/admin.scss
  assets/css/ur-notice.css
  assets/css/ur-notice.scss
  assets/js/admin/settings.js
  assets/js/frontend/user-registration.js
  includes/abstracts/abstract-ur-list-table.php
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-notices.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-license.php
  includes/admin/updater/class-ur-plugin-updater-api.php
  includes/admin/views/html-license-form.php
  includes/class-ur-ajax.php
  includes/class-ur-plugin-updater.php
  includes/class-ur-shortcodes.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  templates/myaccount/form-login.php
  user-registration.php
Labels: Approved, Type: Feature Plugin, Merged, Tested

#379 Tweak - Addons JSON pinged from local
  assets/extensions-json/addon-section.json
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/advanced-fields.png
  assets/extensions-json/sections/images/conditional-logic.jpg
  assets/extensions-json/sections/images/content-restriction.png
  assets/extensions-json/sections/images/customize-my-account.png
  assets/extensions-json/sections/images/extras.png
  assets/extensions-json/sections/images/field-visibility.png
  assets/extensions-json/sections/images/file.png
  assets/extensions-json/sections/images/geolocation.jpg
  assets/extensions-json/sections/images/import-users.png
  assets/extensions-json/sections/images/invite-codes.png
  assets/extensions-json/sections/images/learndash.png
  assets/extensions-json/sections/images/mailchimp.png
  assets/extensions-json/sections/images/multi-part.png
  assets/extensions-json/sections/images/payment-paypal.png
  assets/extensions-json/sections/images/pdf-form-submission.png
  assets/extensions-json/sections/images/profile-connect.png
  assets/extensions-json/sections/images/social.png
  assets/extensions-json/sections/images/stripe.png
  assets/extensions-json/sections/images/style-customizer.png
  assets/extensions-json/sections/images/woo-extension.png
  includes/admin/class-ur-admin-addons.php
  includes/admin/views/html-admin-page-addons.php
Labels: enhancement, Needs Tests

#378 Fix - Sanitization and escaping issue
  includes/class-ur-ajax.php
  includes/class-ur-email-confirmation.php
  includes/class-ur-emailer.php
  includes/class-ur-form-handler.php
  includes/class-ur-frontend-scripts.php
  includes/class-ur-install.php
  includes/class-ur-plugin-updater.php
  includes/class-ur-preview.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  includes/shortcodes/class-ur-shortcode-login.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: bug, Needs Review, Needs Tests
