Repository wpeverest/user-registration, pull requests merged in 2021-06, with the labels that each got.

#349 Tweak - Placement of smart tag filter and content mapping
  includes/class-ur-emailer.php
Labels: Merged, Status: Approved, Status: Tested, enhancement

#344 Add filter for the redirect URL for disable core login redirect
  includes/frontend/class-ur-frontend.php
Labels: Merged, Status: Approved, Status: Tested

#346 Feature Send test email
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/settings/class-ur-settings-email.php
  includes/class-ur-ajax.php
Labels: Feature Request, Impact: Medium, Merged, Status: Approved, Status: Tested

#347 Fix - Auto login conflicts with payment
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
Labels: Impact: Medium, Merged, Status: Approved, Status: Tested, bug

#350 Feature - Gutenberg block for login
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/js/admin/gutenberg/form-block.build.js
  assets/js/admin/gutenberg/form-block.js
  assets/js/frontend/ur-login.js
  includes/class-ur-form-block.php
  includes/functions-ur-template.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: Feature Request, Status: Needs Docs, Status: Needs Review, Status: Needs Tests
