Repository wpeverest/user-registration, pull requests merged in 2021-05, with the labels that each got.

#336 Feature - Edit profile form shortcode
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/my-account-layout.scss
  assets/js/frontend/user-registration.js
  includes/class-ur-form-handler.php
  includes/class-ur-shortcodes.php
  includes/functions-ur-core.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  templates/myaccount/form-edit-profile.php
Labels: Feature Request, Impact: Medium, Merged, Status: Approved, Status: Tested

#338 Fix - Recaptcha issue on login and registration shortcode page
  assets/js/frontend/ur-login.js
  assets/js/frontend/user-registration.js
  includes/class-ur-ajax.php
  includes/class-ur-shortcodes.php
  templates/form-registration.php
Labels: Status: Approved, Status: Ready to Merge, Status: Tested, bug

#335 Enhance - Reset Button in UR Form
  includes/functions-ur-template.php
  templates/form-registration.php
Labels: Merged, Status: Approved, Status: Tested, enhancement

#342 Enhance - Payment slider in range field
  includes/abstracts/abstract-ur-form-field.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Approved, Status: Ready to Merge, Status: Tested, enhancement

#329 Enhance - Valid file type in my account profile picture
  assets/js/frontend/my-account.js
  includes/class-ur-ajax.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Needs Review, Status: Needs Tests, enhancement
