Repository wpeverest/user-registration, pull requests merged in 2021-07, with the labels that each got.

#348 Feature - Form field icons in user registration
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/user-registration.scss
  assets/js/admin/admin.js
  includes/abstracts/abstract-ur-form-field.php
  includes/frontend/class-ur-frontend.php
  includes/functions-ur-template.php
  package-lock.json
  package.json
  templates/form-registration.php
  templates/myaccount/form-login.php
Labels: Approved, Feature Request, Impact: Medium, Merged, Tested

#352 Feature - Login only option
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/functions-ur-core.php
Labels: Approved, Feature Request, Merged, Status: Needs Docs, Tested

#353 Enhance - Select all option in multiple choice field
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/js/frontend/user-registration.js
  includes/abstracts/abstract-ur-form-field.php
  includes/form/settings/class-ur-setting-checkbox.php
  includes/functions-ur-template.php
  templates/myaccount/form-edit-profile.php
Labels: Approved, Merged, Status: Needs Docs, Tested, enhancement

#355 Fix - String translation in edit profile
  templates/myaccount/form-edit-profile.php
Labels: Approved, Merged, Tested, bug

#339 Fix - class translation issue
  includes/abstracts/abstract-ur-form-field.php
  includes/functions-ur-core.php
Labels: Approved, Merged, Tested, bug

#354 Refactor - Metabox and List Table
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/metabox.scss
  includes/abstracts/abstract-ur-list-table.php
  includes/abstracts/abstract-ur-meta-boxes.php
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-registrations-table-list.php
  user-registration.php
Labels: Approved, Ready to Merge, Tested, Type: Refactor

#351 Refactor - Settings page design and codes
  assets/css/_forms.scss
  assets/css/_spacing.scss
  assets/css/admin.scss
  assets/css/components/_card.scss
  assets/css/layout/_header.scss
  assets/css/user-registration.scss
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-integration.php
  includes/admin/settings/emails/class-ur-settings-admin-email.php
  includes/admin/settings/emails/class-ur-settings-awaiting-admin-approval-email.php
  includes/admin/settings/emails/class-ur-settings-email-confirmation.php
  includes/admin/settings/emails/class-ur-settings-profile-details-changed-email.php
  includes/admin/settings/emails/class-ur-settings-registration-approved-email.php
  includes/admin/settings/emails/class-ur-settings-registration-denied-email.php
  includes/admin/settings/emails/class-ur-settings-registration-pending-email.php
  includes/admin/settings/emails/class-ur-settings-reset-password-email.php
  includes/admin/settings/emails/class-ur-settings-successfully-registered-email.php
  includes/admin/views/html-admin-page-export-users.php
  includes/admin/views/html-admin-page-import-export-forms.php
  includes/functions-ur-core.php
Labels: Approved, Merged, Tested, enhancement

#356 Refactor - User registration js codes
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  assets/js/admin/ur-copy.js
  assets/js/frontend/ur-login.js
  assets/js/frontend/user-registration-recaptcha.js
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-assets.php
  includes/class-ur-frontend-scripts.php
  includes/functions-ur-core.php
Labels: Approved, Merged, Tested, enhancement
