Repository wpeverest/user-registration, pull requests merged in 2021-03, with the labels that each got.

#312 Fix - Form Duplication issue with anchor tag
  includes/class-ur-form-handler.php
Labels: Status: Needs Review, Status: Needs Tests, bug

#314 Fix - WYSIWYG field value save and sanitization in edit-profile
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/frontend/class-ur-frontend-form-handler.php
Labels: Status: Needs Tests, bug

#296 Enhancement - Setting page header UI
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/components/_nav.scss
  assets/css/components/_scroll-ui.scss
  assets/css/layout/_header.scss
  assets/css/variables/_colors.scss
  assets/js/admin/admin.js
  assets/js/ur-components/scroll-ui.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/settings/class-ur-settings-page.php
  includes/admin/views/html-admin-settings.php
Labels: Status: Approved, Status: Ready to Merge, Status: Tested, enhancement

#310 Tweak - WordPress 5.7 compatibility
  assets/js/admin/admin.js
  assets/js/admin/backbone-modal.js
  assets/js/admin/settings.js
  assets/js/admin/ur-copy.js
  assets/js/frontend/my-account.js
  assets/js/frontend/password-strength-meter.js
  assets/js/frontend/user-registration.js
  assets/js/ur-components/ur-components.js
  includes/admin/class-ur-admin.php
Labels: Status: Approved, Status: Ready to Merge, Status: Tested, Type: Refactor

#309 Addon - MailerLite Compatibility
  assets/css/_fonts.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/fonts/UserRegistration.eot
  assets/fonts/UserRegistration.svg
  assets/fonts/UserRegistration.ttf
  assets/fonts/UserRegistration.woff
  assets/js/admin/admin.js
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-profile.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
Labels: Status: Approved, Status: Ready to Merge, Status: Tested
