Repository wpeverest/user-registration, pull requests merged in 2021-02, with the labels that each got.

#304 Addon - Range field support
  assets/css/_fonts.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/variables/_colors.scss
  assets/fonts/UserRegistration.eot
  assets/fonts/UserRegistration.svg
  assets/fonts/UserRegistration.ttf
  assets/fonts/UserRegistration.woff
  assets/js/frontend/user-registration.js
  includes/abstracts/abstract-ur-form-field.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Needs Tests, enhancement

#303 Enhance - Limit username length and choice field.
  assets/js/frontend/user-registration-form-validator.js
  assets/js/frontend/user-registration.js
  includes/abstracts/abstract-ur-form-field.php
  includes/class-ur-frontend-scripts.php
  includes/class-ur-shortcodes.php
  includes/form/settings/class-ur-setting-checkbox.php
  includes/form/settings/class-ur-setting-user_login.php
  includes/functions-ur-template.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  templates/myaccount/form-edit-profile.php
Labels: Needs Extensive Test, enhancement

#306 Tweak - Prevent core login for woocommerce shortcode
  includes/frontend/class-ur-frontend.php
Labels: Status: Needs Review, Status: Needs Tests

#305 Dev - Learndash Compatibility
  includes/abstracts/abstract-ur-form-field.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
Labels: Status: Needs Review, Status: Needs Tests

#308 Enhance - Resend Verification Email to User from Admin
  includes/class-ur-email-confirmation.php
  includes/class-ur-user-approval.php
Labels: Status: Needs Docs, Status: Needs Review, Status: Needs Tests, enhancement
