Repository wpeverest/user-registration, pull requests merged in 2022-09, with the labels that each got.

#442 UR-378 Fix - Required field not working when conditional logic enabled.
  includes/form/class-ur-form-field-checkbox.php
  includes/form/class-ur-form-field-country.php
  includes/form/class-ur-form-field-date.php
  includes/form/class-ur-form-field-description.php
  includes/form/class-ur-form-field-display-name.php
  includes/form/class-ur-form-field-email.php
  includes/form/class-ur-form-field-first-name.php
  includes/form/class-ur-form-field-last-name.php
  includes/form/class-ur-form-field-nickname.php
  includes/form/class-ur-form-field-number.php
  includes/form/class-ur-form-field-password.php
  includes/form/class-ur-form-field-privacy-policy.php
  includes/form/class-ur-form-field-radio.php
  includes/form/class-ur-form-field-select.php
  includes/form/class-ur-form-field-text.php
  includes/form/class-ur-form-field-textarea.php
  includes/form/class-ur-form-field-user-confirm-email.php
  includes/form/class-ur-form-field-user-confirm-password.php
  includes/form/class-ur-form-field-user-email.php
  includes/form/class-ur-form-field-user-login.php
  includes/form/class-ur-form-field-user-pass.php
  includes/form/class-ur-form-field-user-url.php
Labels: bug, Approved, Merged, Tested

#441 Tweak - Add field data hook
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-account.php
Labels: Approved, Merged, Tested, compatibility

#435 UR-346 Enhance - Parse smart tag values in appropriate format to display
  includes/class-ur-emailer.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#453 UR-418 Fix - Pending user not listed
  includes/class-ur-email-confirmation.php
Labels: bug, Approved, Merged, Tested

#451 UR-314 Enhance - Add custom fields support to export as csv
  includes/admin/views/html-admin-page-export-users.php
  includes/class-ur-form-handler.php
Labels: Approved, Merged, Tested, compatibility

#452 UR-402 Dev - Compatibility of validate unique field issue in multipart
  assets/js/admin/admin.js
  assets/js/frontend/user-registration.js
Labels: bug, Approved, Merged, Tested

#447 UR-405 Fix - Add field removed trigger
  assets/js/admin/form-builder.js
Labels: Approved, Merged, Tested, compatibility

#449 UR-409 Fix - Misplaced error message for Quantity field.
  assets/js/frontend/user-registration-form-validator.js
Labels: bug, Approved, Merged, Tested

#448 UR-408 Fix - Delete forms while uninstall plugin
  uninstall.php
Labels: bug, Approved, Merged, Tested

#455 UR-413 Dev - Change text typo and grammatical mistake
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/settings.js
  includes/RestApi/class-ur-rest-api.php
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-assets.php
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-integration.php
  includes/admin/views/html-admin-page-forms.php
  includes/form/settings/class-ur-setting-checkbox.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#456 UR-419 Tweak- Install pages notice when onboarding skipped
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-notices.php
  includes/admin/class-ur-admin-welcome.php
  includes/admin/views/html-notice-custom.php
  includes/admin/views/html-notice-install.php
  includes/class-ur-install.php
  includes/functions-ur-core.php
  user-registration.php
Labels: enhancement, Approved, Merged, Tested

#450 UR-397 Fix - Post Submission issue in edit profile when conditional logic applied to required field
  includes/class-ur-form-handler.php
Labels: bug, Approved, Merged, Tested
