Repository wpeverest/user-registration, pull requests merged in 2022-03, with the labels that each got.

#399 Fix - Issues due to wrong phpcs fix
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-settings.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  templates/form-registration.php
Labels: bug, Approved, Ready to Merge, Tested

#397 UR-195 Fix - My Account translation issue
  includes/admin/class-ur-admin-user-list-manager.php
  includes/functions-ur-core.php
  templates/myaccount/navigation.php
Labels: bug, Approved, Ready to Merge, Tested

#390 UR-93 Feature- Getting started page
  .babelrc
  .eslintrc
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-setup-wizard.scss
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/variables/_colors.scss
  assets/images/UR-extensions.png
  assets/images/UR-feature.png
  assets/images/onboard-end.png
  assets/images/onboard-icons/bordered.png
  assets/images/onboard-icons/default.png
  assets/images/onboard-icons/flat.png
  assets/images/onboard-icons/rounded.png
  assets/images/onboard-icons/rounded_edge.png
  assets/js/admin/gutenberg/form-block.build.js
  assets/js/admin/gutenberg/form-block.js
  composer.lock
  includes/RestApi/class-ur-rest-api.php
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-welcome.php
  includes/admin/class-ur-admin.php
  includes/admin/functions-ur-admin.php
  includes/admin/views/html-admin-page-builder-setup.php
  includes/class-ur-form-block.php
  includes/class-ur-install.php
  includes/functions-ur-core.php
  package-lock.json
  package.json
  src/components/App.js
  src/components/common/Header.js
  src/components/common/InputHandler.js
  src/components/screens/GeneralSettings.js
  src/components/screens/InstallPage.js
  src/components/screens/LastPage.js
  src/components/screens/LoginSettings.js
  src/components/screens/MyAccountSettings.js
  src/components/screens/RegistrationSettings.js
  src/context/StateProvider.js
  src/context/gettingStartedContext.js
  src/index.html
  src/index.js
  user-registration.php
  webpack.config.js
Labels: enhancement, Needs Review, Needs Extensive Test, Needs Documentation

#400 UR-239 Fix - Email field empty when field visibility is readonly after profile update
  includes/class-ur-form-handler.php
Labels: bug, Impact: Low, Approved, Ready to Merge, Tested
