Repository wpeverest/user-registration, pull requests merged in 2022-12, with the labels that each got.

#472 Fix - Field not appended in the droppable zone
  assets/js/admin/form-builder.js
Labels: bug, Approved, Merged

#474 UR-541 Fix - User CSV export issue while checkbox or multi select2 exists
  includes/admin/class-ur-admin-export-users.php
Labels: bug, Approved, Merged, Tested

#481 UR-547 Fix - User export issue when form name has special characters
  includes/admin/class-ur-admin-export-users.php
Labels: bug, Approved, Merged, Tested

#478 UR-544 Fix - Delete popup modal for field design.
  assets/css/admin.scss
Labels: bug, Approved, Merged, Tested

#471 UR-504 Fix - Show Password icon in Password Field
  assets/js/frontend/user-registration.js
Labels: bug, Approved, Merged, Tested

#469 Fix - Accordion issue in form builder.
  assets/js/admin/form-builder.js
  includes/abstracts/abstract-ur-form-field.php
Labels: bug, Approved, Merged, Tested

#488 UR-556 Tweak- Add tag for selected my account page
  includes/admin/class-ur-admin.php
Labels: enhancement, Needs Review, Needs Tests, Needs Documentation

#466 UR-507 Fix - Popup design issue in menu
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/components/_modal.scss
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
Labels: enhancement, Approved, Merged, Tested

#487 UR-555 Fix - Gutenberg compatibility issue with my account
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#480 UR-481 Fix - Errors and warnings in the console
  assets/css/jquery-ui/images/ui-bg_flat_0_aaaaaa_40x100.png
  assets/css/jquery-ui/images/ui-bg_flat_75_ffffff_40x100.png
  assets/css/jquery-ui/images/ui-bg_glass_55_fbf9ee_1x400.png
  assets/css/jquery-ui/images/ui-bg_glass_65_ffffff_1x400.png
  assets/css/jquery-ui/images/ui-bg_glass_75_dadada_1x400.png
  assets/css/jquery-ui/images/ui-bg_glass_75_e6e6e6_1x400.png
  assets/css/jquery-ui/images/ui-bg_glass_95_fef1ec_1x400.png
  assets/css/jquery-ui/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  assets/css/jquery-ui/images/ui-icons_222222_256x240.png
  assets/css/jquery-ui/images/ui-icons_2e83ff_256x240.png
  assets/css/jquery-ui/images/ui-icons_454545_256x240.png
  assets/css/jquery-ui/images/ui-icons_888888_256x240.png
  assets/css/jquery-ui/images/ui-icons_cd0a0a_256x240.png
  includes/form/views/admin/admin-country.php
  includes/form/views/admin/admin-date.php
  includes/form/views/admin/admin-description.php
  includes/form/views/admin/admin-display-name.php
  includes/form/views/admin/admin-email.php
  includes/form/views/admin/admin-first-name.php
  includes/form/views/admin/admin-last-name.php
  includes/form/views/admin/admin-nickname.php
  includes/form/views/admin/admin-number.php
  includes/form/views/admin/admin-password.php
  includes/form/views/admin/admin-privacy-policy.php
  includes/form/views/admin/admin-radio.php
  includes/form/views/admin/admin-select.php
  includes/form/views/admin/admin-text.php
  includes/form/views/admin/admin-textarea.php
  includes/form/views/admin/admin-user-confirm-email.php
  includes/form/views/admin/admin-user-confirm-password.php
  includes/form/views/admin/admin-user-email.php
  includes/form/views/admin/admin-user-login.php
  includes/form/views/admin/admin-user-pass.php
  includes/form/views/admin/admin-user-url.php
Labels: bug, Approved, Merged, Tested

#468 UR-502 Fix - Forms table sorting by latest update
  includes/abstracts/abstract-ur-list-table.php
Labels: bug, Approved, Merged, Tested

#475 Tweak - Submit Button Class, Submit Button Text and Form Class label and tooltip text.
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#463 Fix - 'Special Character Validation in Username' and 'Unknown Email' messages not working.
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/class-ur-frontend-scripts.php
  includes/form/class-ur-form-field-user-login.php
Labels: bug, Approved, Merged, Tested

#465 Fix - Form not submitting issue while captcha keys are not set.
  assets/js/frontend/user-registration-recaptcha.js
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
Labels: bug, Approved, Merged, Tested

#482 UR-523 Dev - Payment issues compatibility
  includes/admin/functions-ur-admin.php
  includes/class-ur-ajax.php
Labels: Approved, Merged, Tested, compatibility

#479 Fix - PHP 8.1 Compatibility issue
  includes/admin/class-ur-admin-notices.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/class-ur-admin-status.php
  includes/functions-ur-page.php
Labels: bug, Approved, Merged, Tested
