Repository wpeverest/user-registration, pull requests merged in 2022-11, with the labels that each got.

#457 UR-406 Dev - Stripe refactor compatibility changes.
  assets/js/frontend/user-registration.js
  includes/class-ur-user-approval.php
  includes/frontend/class-ur-frontend-form-handler.php
Labels: Needs Review, Needs Tests, compatibility

#440 UR-341 Enhance - Support links on the checkbox field option
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-profile.php
  includes/class-ur-ajax.php
  includes/form/views/admin/admin-checkbox.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-template.php
Labels: enhancement, Ready to Merge

#446 UR-400 Fix- Disable Default WordPress Login Screen not working on custom login page
  includes/frontend/class-ur-frontend.php
Labels: bug, Approved, Ready to Merge

#459 UR-96 Feature - Form templates
  .eslintrc
  .stylelintrc.json
  assets/css/admin.scss
  assets/css/variables/_colors.scss
  assets/extensions-json/templates/all_templates.json
  assets/extensions-json/templates/images/Profile.jpg
  assets/extensions-json/templates/images/ad-submission-form.png
  assets/extensions-json/templates/images/blood-donor-registration-form.png
  assets/extensions-json/templates/images/boot-camp-registration-form.png
  assets/extensions-json/templates/images/car-race-registration-form.png
  assets/extensions-json/templates/images/conditional-registration.jpg
  assets/extensions-json/templates/images/course.jpg
  assets/extensions-json/templates/images/customer-account-opening-form.png
  assets/extensions-json/templates/images/date-time.jpg
  assets/extensions-json/templates/images/donation.jpg
  assets/extensions-json/templates/images/file-upload.jpg
  assets/extensions-json/templates/images/guest-registration-form.png
  assets/extensions-json/templates/images/hospital-admission-form.png
  assets/extensions-json/templates/images/multiform-1.jpg
  assets/extensions-json/templates/images/multiform.jpg
  assets/extensions-json/templates/images/new-form.png
  assets/extensions-json/templates/images/newsletter-subscribe-form.png
  assets/extensions-json/templates/images/partner-request-registration-form.png
  assets/extensions-json/templates/images/payment.jpg
  assets/extensions-json/templates/images/paypal.jpg
  assets/extensions-json/templates/images/placeholder.png
  assets/extensions-json/templates/images/recaptcha-registration-form.png
  assets/extensions-json/templates/images/recaptcha.jpg
  assets/extensions-json/templates/images/restricted-registration.jpg
  assets/extensions-json/templates/images/social-registration.jpg
  assets/extensions-json/templates/images/sports-camp-registration-form.png
  assets/extensions-json/templates/images/student-registration-form.png
  assets/extensions-json/templates/images/talent-search-registration-form.png
  assets/js/admin/form-builder.js
  assets/js/admin/form-template-controller.js
  assets/js/admin/ur-setup.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-import-export-forms.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin.php
  includes/admin/views/html-admin-page-builder-setup.php
  includes/admin/views/html-admin-page-form-templates.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/functions-ur-core.php
  templates/myaccount/form-edit-profile.php
Labels: Approved, Feature Request, Ready to Merge, Needs Extensive Test

#460 UR-430 Dev - Add hooks to render custom content
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: Needs Review, Needs Tests, compatibility

#464 UR-537 Fix - Error when approving user
  includes/admin/class-ur-admin-notices.php
  includes/functions-ur-core.php
Labels: bug, Impact: High, Approved, Merged, Tested

#476 Fix - Form export issue when the form name has a special character.
  includes/admin/class-ur-admin-import-export-forms.php
Labels: bug, Ready to Merge, Tested

#467 UR-501 Fix - Email verification plain text to link
  includes/admin/settings/emails/class-ur-settings-email-confirmation.php
Labels: bug, Needs Review, Needs Tests

#473 UR-477 Fix - Getting Started Page not working in dev environment.
  includes/admin/class-ur-admin-welcome.php
  includes/admin/class-ur-admin.php
  src/components/App.js
Labels: bug, Needs Review, Needs Tests
