Repository wpeverest/user-registration, pull requests merged in 2022-02, with the labels that each got.

#377 Run Unit Tests and Coding Standards on Pull Request
  .github/workflows/pr-code-sniff.yml
  .gitignore
  .wp-env.json
  composer.json
  composer.lock
  includes/admin/class-ur-admin-export-users.php
  includes/class-ur-email-confirmation.php
  package-lock.json
  package.json
  phpunit.watcher.yml.dist
  phpunit.xml.dist
  tests/.env.example
  tests/bin/phpcs.sh
  tests/phpunit/bootstrap.php
  tests/phpunit/multisite.xml
  tests/wp-config.php
  tests/wp-tests-config.php
Labels: Approved, Merged

#394 Fix - Recaptcha script localization
  includes/functions-ur-core.php
Labels: bug, Needs Extensive Test

#398 UR-233 Feature - hCaptcha
  assets/js/admin/settings.js
  assets/js/frontend/ur-login.js
  assets/js/frontend/user-registration-recaptcha.js
  assets/js/frontend/user-registration.js
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-integration.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/class-ur-frontend-scripts.php
  includes/functions-ur-core.php
  templates/form-registration.php
  templates/myaccount/form-login.php
Labels: Needs Review, Needs Tests, Feature Request

#396 UR-151 Fix - Prevent Dashboard Access
  includes/admin/class-ur-admin.php
  includes/frontend/class-ur-frontend.php
Labels: bug, Approved, Merged, Tested

#392 Fix- Email sender option value while sending a test email
  includes/class-ur-ajax.php
Labels: bug, Impact: Low, Needs Review, Needs Tests

#393 UR-221 Fix - PHP 8.0 compatibility
  includes/abstracts/abstract-ur-form-field.php
  includes/class-ur-preview.php
  includes/class-ur-shortcodes.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/frontend/class-ur-frontend.php
  includes/functions-ur-core.php
  includes/shortcodes/class-ur-shortcode-login.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: bug, Approved, Merged, Tested

#395 UR-231 Feature - Recaptcha v2 invisible and threshold score
  assets/js/admin/settings.js
  assets/js/frontend/user-registration-recaptcha.js
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-integration.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Feature Request, Merged, Tested
