Repository wpeverest/user-registration, pull requests merged in 2022-07, with the labels that each got.

#421 UR-335 Fix - Profile Picture removed when profile updated
  includes/admin/views/html-notice-key-activated.php
  templates/myaccount/form-edit-profile.php
Labels: bug, Approved, Needs Tests, Ready to Merge

#418 UR-325 Fix - View details link in plugins row action broken for addons
  includes/admin/updater/class-ur-addon-updater.php
Labels: bug, Approved, Ready to Merge, Tested

#420 UR-272 Dev - Validate unique field compatibility
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
Labels: Approved, Feature Request, Ready to Merge, Tested, Needs Documentation

#422 UR-316 Feature - Approve User via Email Token Link and Global Settings Title Changes
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.css.map
  assets/css/menu.scss
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/ur-notice-rtl.css
  assets/css/ur-notice.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/user-registration.css.map
  assets/css/user-registration.scss
  assets/js/admin/admin.js
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-integration.php
  includes/admin/settings/class-ur-settings-license.php
  includes/admin/settings/class-ur-settings-misc.php
  includes/admin/settings/emails/class-ur-settings-admin-email.php
  includes/admin/views/html-admin-page-export-users.php
  includes/admin/views/html-admin-page-import-export-forms.php
  includes/class-ur-email-approval.php
  includes/class-ur-emailer.php
  includes/functions-ur-core.php
  package-lock.json
  package.json
  templates/myaccount/form-login.php
  user-registration.php
Labels: Feature Request

#430 Enhance / Keyboard Shortcuts Dialog
  assets/css/admin.scss
  assets/css/jquery-confirm/jquery-confirm.css
  assets/js/admin/form-builder.js
  assets/js/jquery-confirm/jquery-confirm.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/views/html-admin-page-forms.php
Labels: enhancement, Approved, Merged, Tested

#426 UR-352 Fix - File upload path permission denied due to non-existent file upload directory.
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
Labels: bug, Approved, Merged, Tested

#424 UR-342 - Remove whitespace before form fields
  assets/css/user-registration.scss
  assets/js/frontend/user-registration-form-validator.js
  assets/js/frontend/user-registration.js
Labels: bug, Approved, Merged, Tested

#423 Fix - Date Range not accepting end date
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#431 UR-350 Fix - Field option value dynamically not rendered in form builder
  assets/js/admin/form-builder.js
Labels: bug, Approved, Merged, Tested

#427 UR-315 Dev - Frontend listing advanced filters compatibility.
  assets/css/admin.scss
  assets/css/metabox.scss
  includes/abstracts/abstract-ur-meta-boxes.php
Labels: enhancement, Approved, Merged, Tested
