Repository wpeverest/user-registration, pull requests merged in 2022-04, with the labels that each got.

#405 UR-265 Enhance - Active status on emails settings
  includes/admin/settings/class-ur-settings-email.php
Labels: enhancement, Approved, Ready to Merge

#401 UR-247 Fix- Admin approval keeps switching to pending from user profile
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin-user-manager.php
Labels: bug, Impact: Low, Approved, Merged, Tested

#411 UR-275 Fix - Default reset password and myaccount design issue
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/my-account-layout.scss
  includes/frontend/class-ur-frontend.php
  package-lock.json
Labels: bug, Impact: Low, Approved, Merged, Tested

#407 UR-243 Fix - Profile Pic upload issue from edit profile.
  includes/class-ur-emailer.php
  includes/class-ur-form-handler.php
  templates/myaccount/form-edit-profile.php
Labels: bug, Needs Review, Needs Tests

#408 UR-274 Enhance - Keyboard shortcut in form builder
  .eslintrc
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-assets.php
Labels: enhancement, Approved, Ready to Merge

#403 UR-45 Dev - PDF enhancements
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-settings.php
Labels: enhancement, Approved, Merged, Tested

#406 UR-181 Feature - Autocomplete Address Field with Map
  assets/js/admin/form-builder.js
  includes/form/settings/class-ur-setting-text.php
  includes/functions-ur-template.php
Labels: Approved, Feature Request, Merged, Tested
