Repository wpeverest/user-registration, pull requests merged in 2022-08, with the labels that each got.

#438 UR-392 Tweak - Replace incremental file name function with wordpress default
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#436 UR-358 Refactor - Remove field icon code
  includes/functions-ur-template.php
Labels: Approved, Type: Refactor, Merged, Tested

#434 UR-383 Refactor - Replace jQuery-tiptip with Tooltipster for tooltip
  Gruntfile.js
  assets/css/admin.scss
  assets/css/tooltipster/tooltipster-sideTip-borderless.min.css
  assets/css/tooltipster/tooltipster.bundle.css
  assets/css/tooltipster/tooltipster.bundle.min.css
  assets/css/user-registration.scss
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  assets/js/admin/ur-copy.js
  assets/js/frontend/user-registration-form-validator.js
  assets/js/tooltipster/tooltipster.bundle.js
  assets/js/tooltipster/tooltipster.bundle.min.js
  includes/admin/class-ur-admin-assets.php
  includes/class-ur-frontend-scripts.php
  includes/functions-ur-template.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: enhancement, Approved, dependencies, Merged, Tested

#439 UR-373 Fix - Error thrown when uploaded file is not found in upload directory
  templates/myaccount/form-edit-profile.php
Labels: bug, Approved, Merged, Tested

#437 UR-390 Fix - Redirection after registration not working with block
  includes/functions-ur-template.php
Labels: bug, Approved, Merged, Tested

#443 Fix - Show Tooltip after required icon
  includes/functions-ur-template.php
Labels: enhancement, Approved, Merged, Tested
