Repository wpeverest/user-registration, pull requests merged in 2022-01, with the labels that each got.

#373 UR-100 Dev - Hooks for custom advance setting
  assets/js/admin/form-builder.js
  includes/form/settings/class-ur-setting-checkbox.php
  includes/form/settings/class-ur-setting-country.php
  includes/form/settings/class-ur-setting-date.php
  includes/form/settings/class-ur-setting-description.php
  includes/form/settings/class-ur-setting-display_name.php
  includes/form/settings/class-ur-setting-email.php
  includes/form/settings/class-ur-setting-first_name.php
  includes/form/settings/class-ur-setting-last_name.php
  includes/form/settings/class-ur-setting-nickname.php
  includes/form/settings/class-ur-setting-number.php
  includes/form/settings/class-ur-setting-password.php
  includes/form/settings/class-ur-setting-radio.php
  includes/form/settings/class-ur-setting-select.php
  includes/form/settings/class-ur-setting-text.php
  includes/form/settings/class-ur-setting-textarea.php
  includes/form/settings/class-ur-setting-user_confirm_email.php
  includes/form/settings/class-ur-setting-user_confirm_password.php
  includes/form/settings/class-ur-setting-user_email.php
  includes/form/settings/class-ur-setting-user_login.php
  includes/form/settings/class-ur-setting-user_pass.php
  includes/form/settings/class-ur-setting-user_url.php
Labels: Approved, Feature Request, Ready to Merge, Tested

#376 UR-169 Enhance - Size limit on profile picture field in edit profile page
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-assets.php
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Approved, Merged, Tested

#383 UR-189 Fix - Resend verification not working when ajax login is enabled
  includes/class-ur-user-approval.php
Labels: bug, Approved, Ready to Merge, Tested

#382 UR-91 Enhance - Extension page design and addons installation.
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/advanced-fields.png
  assets/extensions-json/sections/images/conditional-logic.jpg
  assets/extensions-json/sections/images/conditional-logic.png
  assets/extensions-json/sections/images/content-restriction.png
  assets/extensions-json/sections/images/customize-my-account.png
  assets/extensions-json/sections/images/email-templates.png
  assets/extensions-json/sections/images/extras.png
  assets/extensions-json/sections/images/field-visibility.png
  assets/extensions-json/sections/images/file.png
  assets/extensions-json/sections/images/frontend-listing.png
  assets/extensions-json/sections/images/geolocation.jpg
  assets/extensions-json/sections/images/geolocation.png
  assets/extensions-json/sections/images/import-users.png
  assets/extensions-json/sections/images/invite-codes.png
  assets/extensions-json/sections/images/learndash.png
  assets/extensions-json/sections/images/mailchimp.png
  assets/extensions-json/sections/images/mailerlite.png
  assets/extensions-json/sections/images/multi-part.png
  assets/extensions-json/sections/images/payment-paypal.png
  assets/extensions-json/sections/images/pdf-form-submission.png
  assets/extensions-json/sections/images/profile-connect.png
  assets/extensions-json/sections/images/social.png
  assets/extensions-json/sections/images/stripe.png
  assets/extensions-json/sections/images/style-customizer.png
  assets/extensions-json/sections/images/woo-extension.png
  assets/extensions-json/sections/images/zapier.png
  includes/admin/class-ur-admin-addons.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/views/html-admin-page-addons.php
  includes/class-ur-plugin-updater.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#384 UR-192 Fix - File upload data not updated in profile details changed email
  includes/class-ur-emailer.php
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#385 UR-205 Fix - Profile picture remove, update and save on the edit profile page
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  templates/myaccount/form-edit-profile.php
Labels: bug, Approved, Merged, Tested

#386 Dev -Hooks for save btn in profile details
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Approved, Merged, Tested

#375 UR-107 Feature - Combine two login options
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin-user-manager.php
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-email-confirmation.php
  includes/class-ur-emailer.php
  includes/class-ur-user-approval.php
Labels: Approved, Feature Request, Ready to Merge, Needs Documentation
