Repository wpeverest/user-registration, pull requests merged in 2023-02, with the labels that each got.

#504 UR-496 Enhance - Trigger Successful Registration email after email confirmation done by user.
  includes/class-ur-email-confirmation.php
  includes/class-ur-emailer.php
Labels: enhancement, Status: Needs Docs, Merged

#505 Enhancement - View Form Link After Importing
  includes/admin/class-ur-admin-import-export-forms.php
Labels: enhancement, Approved, Merged, Tested

#502 UR-715 Smart tag issue for file in emails.
  includes/admin/class-ur-admin-export-users.php
  includes/admin/class-ur-admin-form-templates.php
  includes/functions-ur-core.php
  templates/myaccount/form-edit-profile.php
Labels: bug, Approved, Merged, Tested

#485 Feature - Shortcode for 'Change Password' Page.
  includes/class-ur-shortcodes.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: Approved, Feature Request, Merged, Tested

#510 UR-729 Fix - UR myaccount redirection issue on plain permalink structure
  includes/class-ur-form-handler.php
Labels: bug, Approved, Ready to Merge, Tested

#509 Tweak - Field option should be clickable even when no any field is selected.
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-form-templates.php
  includes/admin/views/html-admin-page-form-templates.php
  includes/admin/views/html-admin-page-forms.php
  includes/functions-ur-page.php
Labels: enhancement, Approved, Merged, Tested

#470 UR-536 Fix - Reset and incorrect password message appears at same time
  assets/js/frontend/ur-login.js
  includes/class-ur-form-handler.php
  includes/shortcodes/class-ur-shortcode-login.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: bug, Approved, Ready to Merge, Tested

#496 UR-172 Dev - Compatibility for unsupported currency validation message
  assets/js/admin/form-builder.js
Labels: enhancement, Approved, Ready to Merge, Tested

#506 Fix - Email content override not working.
  assets/js/admin/form-builder.js
Labels: bug, Approved, Ready to Merge, Tested

#516 UR-716 Fix - Field Visibility Setting value not saving in safari
  assets/js/admin/form-builder.js
Labels: bug, Approved, Ready to Merge, Tested

#515 Tweak - Multiple form import export at a time
  includes/admin/class-ur-admin-import-export-forms.php
  includes/admin/views/html-admin-page-import-export-forms.php
Labels: enhancement, Approved, Ready to Merge, Tested

#513 UR-665 Enhancement - Enable disable email from email list table global email setting
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/settings/class-ur-settings-email.php
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Tested

#508 Feature - Email confirmation for email editing on the edit profile page.
  assets/js/frontend/my-account.js
  assets/js/frontend/user-registration.js
  includes/class-ur-ajax.php
  includes/class-ur-email-confirmation.php
  includes/class-ur-form-handler.php
  includes/functions-ur-notice.php
  includes/functions-ur-template.php
  templates/myaccount/form-edit-profile.php
Labels: Approved, Feature Request, Ready to Merge, Tested

#519 Usage tracking implementation
  includes/admin/settings/class-ur-settings-misc.php
  includes/class-ur-cron.php
  includes/stats/class-ur-stats.php
  user-registration.php
Labels: Needs Review, Needs Tests

#512 Deactivation popup
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/deactivation-feedback-rtl.css
  assets/css/deactivation-feedback.css
  assets/css/deactivation-feedback.scss
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/js/admin/deactivation-feedback.js
  assets/js/admin/deactivation-feedback.min.js
  assets/js/admin/plugins.js
  assets/js/admin/plugins.min.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-deactivation-feedback.php
  includes/admin/class-ur-admin.php
  includes/admin/views/html-deactivation-popup.php
  includes/admin/views/html-notice-deactivation.php
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Ready to Merge, Tested

#518 UR-622 Enhancement - Setup wizard design
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-setup-wizard.scss
  assets/css/variables/_colors.scss
  assets/images/onboard-icons/advanced-fields.png
  assets/images/onboard-icons/carret-down.svg
  assets/images/onboard-icons/content-restriction.png
  assets/images/onboard-icons/customize-my-account.png
  assets/images/onboard-icons/green-tick-icon.png
  assets/images/onboard-icons/horizontal.png
  assets/images/onboard-icons/logo.png
  assets/images/onboard-icons/style-customizer.png
  assets/images/onboard-icons/vertical.png
  assets/images/onboard-icons/woo-extension.png
  includes/RestApi/class-ur-rest-api.php
  includes/abstracts/abstract-ur-list-table.php
  includes/admin/class-ur-admin-welcome.php
  package-lock.json
  package.json
  src/components/App.js
  src/components/common/ConsentModal.js
  src/components/common/Header.js
  src/components/common/InputHandler.js
  src/components/screens/GeneralSettings.js
  src/components/screens/InstallPage.js
  src/components/screens/LastPage.js
  src/components/screens/LoginSettings.js
  src/components/screens/MyAccountSettings.js
  src/components/screens/RegistrationSettings.js
  src/context/gettingStartedContext.js
Labels: enhancement, Approved, Ready to Merge, Tested

#493 UR-588 Tweak - Refactor js for preview password
  assets/js/frontend/ur-common.js
  assets/js/frontend/user-registration.js
  includes/class-ur-frontend-scripts.php
  includes/class-ur-shortcodes.php
  includes/shortcodes/class-ur-shortcode-login.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: enhancement, Approved, Merged, Tested

#514 UR-631 Profile Picture Refactor
  assets/js/frontend/my-account.js
  assets/js/frontend/user-registration.js
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/frontend/class-ur-frontend.php
  includes/functions-ur-core.php
  templates/myaccount/form-edit-profile.php
Labels: Approved, Type: Refactor, Ready to Merge, Tested

#507 UR-630 Dev - File upload refactor compatibility
  assets/js/frontend/my-account.js
  assets/js/frontend/user-registration.js
  includes/class-ur-ajax.php
  includes/class-ur-email-approval.php
  includes/class-ur-email-confirmation.php
  includes/class-ur-emailer.php
  includes/class-ur-form-handler.php
  includes/class-ur-user-approval.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/frontend/class-ur-frontend.php
  includes/functions-ur-core.php
  templates/myaccount/form-edit-profile.php
Labels: Approved, Type: Refactor, Ready to Merge, Tested, compatibility

#521 UR-572 Tweak - Notice Improvisation and added new consent notice.
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/extensions-json/sections/all_extensions.json
  includes/admin/class-ur-admin.php
  includes/admin/functions-ur-admin.php
  includes/admin/views/html-notice-promotional.php
  includes/class-ur-ajax.php
  includes/class-ur-install.php
  src/components/screens/RegistrationSettings.js
Labels: enhancement, Approved, Type: Refactor, Merged, Tested
