Repository wpeverest/user-registration, pull requests merged in 2023-05, with the labels that each got.

#552 Feature - PHP Deprecation notice
  includes/admin/class-ur-admin.php
  includes/admin/views/html-notice-php-deprecation.php
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Merged, Tested

#550 Tweak - Check captcha keys while setting up captcha for form
  assets/js/admin/form-builder.js
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Merged, Tested

#539 Dev - Dependency for conditional logic for the submit button.
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
  templates/form-registration.php
Labels: Approved, Feature Request, Merged, Tested

#536 Enhancement - Hidden field
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  includes/abstracts/abstract-ur-field-settings.php
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-menus.php
  includes/class-ur-emailer.php
  includes/class-ur-shortcodes.php
  includes/class-ur-smart-tags.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: enhancement, Approved, Merged, Tested, Needs Documentation

#527 UR-596 Tweak - Value Based Review Notice.
  assets/images/UR-logo.gif
  includes/admin/class-ur-admin.php
  includes/admin/functions-ur-admin.php
  includes/admin/views/html-notice-promotional.php
Labels: enhancement, Approved, Merged, Tested

#554 UR-457 Feature - Search global settings.
  assets/css/settings-rtl.css
  assets/css/settings.css
  assets/css/settings.scss
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-import-export.php
  includes/admin/settings/class-ur-settings-integration.php
  includes/admin/settings/class-ur-settings-license.php
  includes/admin/settings/class-ur-settings-misc.php
  includes/class-ur-ajax.php
  user-registration.zip
Labels: Needs Review, Needs Tests, Feature Request, Needs Documentation

#533 UR-801 Uniform boolean setting value saving and retrieval
  includes/class-ur-ajax.php
  includes/class-ur-cron.php
  includes/class-ur-email-confirmation.php
  includes/class-ur-emailer.php
  includes/class-ur-form-handler.php
  includes/class-ur-post-types.php
  includes/class-ur-user-approval.php
  includes/frontend/class-ur-frontend.php
  includes/functions-ur-core.php
  includes/functions-ur-page.php
  includes/functions-ur-template.php
  includes/stats/class-ur-stats.php
  templates/myaccount/dashboard.php
  templates/myaccount/form-edit-password.php
  templates/myaccount/form-edit-profile.php
  templates/myaccount/form-login.php
  templates/myaccount/form-reset-password.php
  uninstall.php
  user-registration.zip
Labels: enhancement, Approved, Merged, Tested

#545 UR-850 Enhance - Form Builder Design
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/deactivation-feedback-rtl.css
  assets/css/deactivation-feedback.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/ur-notice-rtl.css
  assets/css/ur-notice.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/variables/_colors.scss
  assets/css/variables/_structure.scss
  assets/css/variables/_variables.scss
  assets/images/arrow-left-icon.svg
  assets/images/icons/clippy.svg
  assets/images/icons/copy-icon.svg
  assets/images/icons/lock-icon.png
  assets/images/icons/maximize.svg
  assets/images/icons/minimize.svg
  assets/images/icons/ur-arrow-down.svg
  assets/images/icons/ur-lock-icon.svg
  assets/images/icons/ur-pro-icon.png
  assets/images/icons/ur-right-arrow.svg
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  composer.json
  composer.lock
  includes/abstracts/abstract-ur-field-settings.php
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-profile.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/views/html-admin-page-forms.php
  includes/class-ur-ajax.php
  includes/class-ur-autoloader.php
  includes/form/class-ur-form-field-date.php
  includes/form/settings/class-ur-setting-checkbox.php
  includes/form/settings/class-ur-setting-date.php
  includes/form/settings/class-ur-setting-user_login.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  includes/validation/class-ur-form-validation.php
  phpcs.xml
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Approved, Merged, Tested, Needs Documentation

#556 Fixed/email toggle save issue
  includes/class-ur-ajax.php
Labels: bug, Approved, Merged, Tested

#555 Dev - Dependency for Profile Completeness
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-assets.php
  includes/class-ur-ajax.php
  templates/myaccount/form-edit-profile.php
Labels: Status: Needs Docs, Needs Review, Needs Tests, Feature Request

#549 Enhance - Redirection after registration
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  includes/admin/functions-ur-admin.php
  includes/class-ur-install.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  includes/functions-ur-update.php
  templates/form-registration.php
Labels: enhancement, Approved, Merged, Tested, Needs Documentation

#558 UR-917 Dev - Compatibility for enabling/disabling cropping in profile picture field.
  includes/abstracts/abstract-ur-field-settings.php
  includes/abstracts/abstract-ur-form-field.php
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Approved, Merged, Tested
