Repository wpeverest/user-registration, pull requests merged in 2023-08, with the labels that each got.

#585 UR-989 Feature - User registered language with smart tag.
  includes/class-ur-smart-tags.php
  includes/frontend/class-ur-frontend-form-handler.php
Labels: Approved, Feature Request, Merged, Tested

#582 Tweak - Input box highlighting
  assets/css/user-registration.scss
  assets/js/frontend/user-registration-form-validator.js
Labels: enhancement, Approved, Merged, Tested

#581 Fix - Registration page getting redirected
  includes/functions-ur-template.php
Labels: bug, Approved, Ready to Merge, Tested

#578 Fix - Add new form and click on scratch and enter any name and cancel
  assets/js/admin/ur-setup.js
Labels: bug, Approved, Ready to Merge, Tested

#584 Enhancement - Unique id smart tag
  includes/class-ur-smart-tags.php
Labels: enhancement, Approved, Merged, Tested

#579 UR-1083 Fix - Make login shortcode compatible with all editors
  includes/frontend/class-ur-frontend.php
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#587 UR-1121 Fix - Conflict with TranslatePress
  includes/functions-ur-page.php
Labels: bug, Approved, Merged, Tested

#586 UR-1116 Fix - Lost Password not working for translated myaccount page.
  includes/functions-ur-page.php
Labels: bug, Approved, Tested

#551 UR-830 Feature - Email preview
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/emails/class-ur-settings-admin-email.php
  includes/admin/settings/emails/class-ur-settings-awaiting-admin-approval-email.php
  includes/admin/settings/emails/class-ur-settings-email-confirmation.php
  includes/admin/settings/emails/class-ur-settings-profile-details-changed-email.php
  includes/admin/settings/emails/class-ur-settings-registration-approved-email.php
  includes/admin/settings/emails/class-ur-settings-registration-denied-email.php
  includes/admin/settings/emails/class-ur-settings-registration-pending-email.php
  includes/admin/settings/emails/class-ur-settings-reset-password-email.php
  includes/admin/settings/emails/class-ur-settings-successfully-registered-email.php
  includes/class-ur-emailer.php
  includes/class-ur-preview.php
  includes/functions-ur-core.php
  templates/email-preview.php
Labels: Approved, Feature Request, Ready to Merge, Tested

#594 UR-903 Tweak - Revamp deactivation pop items
  assets/css/deactivation-feedback.scss
  includes/admin/class-ur-admin-deactivation-feedback.php
  includes/admin/views/html-deactivation-popup.php
Labels: enhancement, Approved, Merged, Tested

#591 UR-1132 Fix - Invalid Myaccount link for it's endpoints .
  includes/class-ur-emailer.php
  includes/class-ur-form-handler.php
  includes/functions-ur-page.php
Labels: bug, Approved, Merged, Tested

#588 UR-573 Feature - Pattern validation for input fields
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  includes/abstracts/abstract-ur-field-settings.php
  includes/class-ur-emailer.php
  includes/class-ur-smart-tags.php
Labels: Approved, Feature Request, Merged, Tested, Needs Documentation

#593 UR-1052 Enhance - Custom hold time before redirection after registration
  assets/js/admin/admin.js
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Needs Review, Merged, Tested, Needs Documentation

#589 UR-818 Fix - Submitting issue for conditionally hidden fields
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#583 Enhancement - Create a menu to show the login form shortcode
  assets/css/admin.scss
  assets/css/settings.scss
  assets/images/login_form.png
  assets/js/admin/ur-copy.js
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-registrations-table-list.php
  includes/admin/views/html-login-page-forms.php
Labels: enhancement, Approved, Merged, Tested, Needs Documentation

#592 UR-821 Dev - Compatibility for enabling/disabling taking picture from the webcam.
  includes/abstracts/abstract-ur-form-field.php
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Approved, Merged, Tested

#597 UR-1130 Fix - Incorrect filtering of pending users
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin-user-manager.php
Labels: bug, Approved, Merged, Tested

#596 UR-1036 Feature - Cloudflare turnstile captcha integration
  assets/js/admin/settings.js
  assets/js/frontend/ur-login.js
  assets/js/frontend/user-registration-recaptcha.js
  assets/js/frontend/user-registration.js
  includes/admin/settings/class-ur-settings-captcha.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/class-ur-frontend-scripts.php
  includes/functions-ur-core.php
Labels: Approved, Feature Request, Ready to Merge, Needs Documentation
