Repository wpeverest/user-registration, pull requests merged in 2023-01, with the labels that each got.

#499 Fix - Apply proper escaping for general settings fields to prevent XSS attacks.
  includes/abstracts/abstract-ur-form-field.php
Labels: bug, Approved, Merged, Tested

#497 UR-684 Fix- Disallow reset password for not approved users.
  includes/class-ur-email-confirmation.php
  includes/class-ur-user-approval.php
Labels: bug, Approved, Merged, Tested

#495 Enhance - Form template publish to remote server
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/images/templates/blank.png
  assets/images/templates/placeholder.png
  assets/js/admin/form-template-controller.js
  assets/js/admin/form-template-controller.min.js
  assets/js/admin/form-templates.js
  assets/js/admin/form-templates.min.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-form-templates.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin.php
  includes/admin/views/html-admin-page-form-templates.php
Labels: enhancement, Approved, Merged, Tested

#490 Fix - Flatpickr throwing an error in console.
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-profile.php
  includes/functions-ur-template.php
Labels: bug, Approved, Merged, Tested

#489 UR-458 Dev - Email domain denyist
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/form/class-ur-form-field-email.php
  includes/frontend/class-ur-frontend-form-handler.php
Labels: enhancement, Approved, Merged
