Repository wpeverest/user-registration, pull requests merged in 2023-10, with the labels that each got.

#613 Fix - Escaping issue in redirect URL.
  templates/form-registration.php
Labels: bug, Approved, Merged, Tested

#612 UR-1204 jQuery validation library updated to 1.19.5
  assets/js/frontend/jquery.validate.js
  assets/js/frontend/jquery.validate.min.js
  includes/class-ur-frontend-scripts.php
Labels: enhancement, Approved, Merged, Tested

#605 UR-1186 Tweak - Addons content made concrete and design to make it fit
  assets/images/onboard-icons/advanced-fields.png
  assets/images/onboard-icons/content-restriction.png
  assets/images/onboard-icons/customize-my-account.png
  assets/images/onboard-icons/woo-extension.png
  src/components/screens/LastPage.js
Labels: enhancement, Approved, Merged, Tested

#602 UR-1059 Enhance - Links in admin bar menu
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested, Needs Documentation

#598 UR-576 Fix - Select All button not working in Nav Menus
  assets/js/admin/form-modal.js
  includes/admin/class-ur-admin-menus.php
Labels: bug, Approved, Merged, Tested

#599 Tweak - Redirect url as slug in login and my account shortcode
  includes/class-ur-shortcodes.php
  includes/functions-ur-core.php
  includes/shortcodes/class-ur-shortcode-login.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: enhancement, Approved, Merged, Tested, Needs Documentation

#604 UR-1035 Compatibility custom captcha
  assets/css/_fonts.scss
  assets/fonts/UserRegistration.eot
  assets/fonts/UserRegistration.svg
  assets/fonts/UserRegistration.ttf
  assets/fonts/UserRegistration.woff
  assets/js/admin/form-builder.js
  includes/abstracts/abstract-ur-form-field.php
  templates/myaccount/form-edit-profile.php
Labels: Approved, Feature Request, Merged, Tested, Needs Documentation

#601 UR-870 Enhance - Test captcha from settings
  assets/css/settings.scss
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-captcha.php
Labels: enhancement, Approved, Merged, Tested, Needs Documentation

#607 UR-1201 Fix - UR Settings collapsible header issue.
  assets/js/admin/settings.js
Labels: bug, Approved, Merged, Tested

#603 UR-1049 profile details updated email to user
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/emails/class-ur-settings-profile-details-updated-email.php
  includes/class-ur-emailer.php
  wpml-config.xml
Labels: Approved, Feature Request, Merged, Tested

#595 UR-1139 Refactor - Handle user status properly
  assets/js/admin/form-settings.min.js
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin-user-manager.php
  includes/class-ur-email-approval.php
  includes/class-ur-email-confirmation.php
  includes/class-ur-emailer.php
  includes/class-ur-user-approval.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-account.php
  includes/functions-ur-core.php
Labels: Approved, Type: Refactor, Merged, Tested

#610 UR-1174 Enhance - Send user approval link also in admin approval after email confirmation
  assets/js/admin/admin.js
  includes/class-ur-email-approval.php
  includes/class-ur-emailer.php
Labels: enhancement, Approved, Merged, Tested

#590 UR-749 Dev - Merge two duplicate methods on form validation
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/functions-ur-form.php
  includes/validation/class-ur-form-validation.php
  user-registration.php
Labels: Approved, Type: Refactor, Merged, Tested

#609 Tweak - Save the user IP on the user meta.
  includes/class-ur-form-handler.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Ready to Merge, Tested

#606 Feature - UR form fields integration on woo commerce product page.
  assets/js/frontend/user-registration-form-validator.js
  includes/functions-ur-template.php
Labels: Approved, Feature Request, Merged, Tested, Needs Documentation

#611 UR-805 Enhance - log all fatal errors and delete all logs option
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-status.php
  includes/admin/views/html-admin-page-status-logs.php
  includes/functions-ur-core.php
  includes/log-handlers/class-ur-log-handler-file.php
  user-registration.php
Labels: enhancement, Approved, Merged, Tested

#608 UR-1200 Feature - Admin image uploader module
  assets/js/admin/form-settings.js
  includes/admin/class-ur-admin-assets.php
  templates/form-registration.php
Labels: enhancement, Approved, Ready to Merge, Tested
