Repository wpeverest/user-registration, pull requests merged in 2023-03, with the labels that each got.

#500 UR-637 Refactor - Backend validation for form data
  includes/class-ur-ajax.php
  includes/class-ur-cron.php
  includes/class-ur-form-handler.php
  includes/form/class-ur-form-field-checkbox.php
  includes/form/class-ur-form-field-country.php
  includes/form/class-ur-form-field-date.php
  includes/form/class-ur-form-field-description.php
  includes/form/class-ur-form-field-display-name.php
  includes/form/class-ur-form-field-email.php
  includes/form/class-ur-form-field-first-name.php
  includes/form/class-ur-form-field-last-name.php
  includes/form/class-ur-form-field-nickname.php
  includes/form/class-ur-form-field-number.php
  includes/form/class-ur-form-field-password.php
  includes/form/class-ur-form-field-privacy-policy.php
  includes/form/class-ur-form-field-radio.php
  includes/form/class-ur-form-field-select.php
  includes/form/class-ur-form-field-text.php
  includes/form/class-ur-form-field-textarea.php
  includes/form/class-ur-form-field-user-confirm-email.php
  includes/form/class-ur-form-field-user-confirm-password.php
  includes/form/class-ur-form-field-user-email.php
  includes/form/class-ur-form-field-user-pass.php
  includes/form/class-ur-form-field-user-url.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/validation/class-ur-form-validation.php
  includes/validation/class-ur-setting-validation.php
  includes/validation/class-ur-validation.php
  user-registration.php
Labels: Needs Review, Type: Refactor, On Hold, Needs Extensive Test, Security

#530 UR-752 Fix - Year not displayed on min max date field option
  assets/js/admin/form-builder.js
Labels: bug, Approved, Ready to Merge, Tested

#526 Tweak - Default value for country field
  assets/js/frontend/user-registration-form-validator.js
  includes/form/settings/class-ur-setting-country.php
  includes/form/views/admin/admin-user-confirm-email.php
  includes/form/views/admin/admin-user-confirm-password.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Ready to Merge, Tested

#529 UR-788 Tweak - Make reason required for other option
  assets/js/admin/deactivation-feedback.js
Labels: enhancement, Approved, Merged, Tested

#535 UR-792 Fix - Required icon not displaying properly.
  assets/js/admin/form-builder.js
  includes/abstracts/abstract-ur-form-field.php
Labels: bug, Approved, Merged, Tested

#534 UR-798 Fix - Vulnerability PHP Object injection and send test email by non privileged user.
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-assets.php
  includes/class-ur-ajax.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: bug, Approved, Merged, Tested

#523 UR-677 Fix - reCAPTCHA Registration Form templates don't create reCAPTCHA
  assets/js/admin/ur-setup.js
  includes/admin/class-ur-admin-form-templates.php
  includes/class-ur-ajax.php
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#522 UR-735 Fix - Strip Unwanted fields from conditional rules field
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#532 UR-499 Global settings input validation
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-misc.php
  includes/validation/class-ur-form-validation.php
  includes/validation/class-ur-setting-validation.php
  includes/validation/class-ur-validation.php
  user-registration.php
Labels: enhancement, Approved, Merged, Tested, Security

#528 UR-719 Add - Global Settings
  includes/stats/class-ur-stats.php
Labels: Approved, Merged, Tested
