Repository wpeverest/user-registration, pull requests merged in 2023-11, with the labels that each got.

#626 UR-1252 Tweak - Compatibility with newly introduced ThemeGrill Agency Plan.
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/conversational-forms.png
  assets/js/admin/ur-setup.js
  includes/admin/class-ur-admin-menus.php
  includes/class-ur-ajax.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#614 UR-1219 Fix - Assign user role conditionally not working in multisite
  includes/class-ur-emailer.php
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#625 Tweak - Validation error message in fields.
  includes/form/class-ur-form-field-checkbox.php
  includes/form/class-ur-form-field-country.php
  includes/form/class-ur-form-field-date.php
  includes/form/class-ur-form-field-number.php
  includes/form/class-ur-form-field-password.php
  includes/form/class-ur-form-field-radio.php
  includes/form/class-ur-form-field-text.php
  includes/form/class-ur-form-field-user-email.php
  includes/form/class-ur-form-field-user-login.php
Labels: enhancement, Approved, Merged, Tested

#621 Dev - Form restriction addon
  assets/js/admin/form-builder.js
  includes/class-ur-shortcodes.php
Labels: Approved, Merged, Tested, Needs Documentation

#619 UR-1237 Enhancement - My account logout redirection to external url.
  includes/functions-ur-account.php
  includes/functions-ur-template.php
Labels: enhancement, Approved, Merged, Tested

#618 UR-1057 Tweak - Improve success message after registration
  assets/js/frontend/user-registration.js
  includes/functions-ur-core.php
Labels: enhancement, Approved, Ready to Merge, Tested
