Repository wpeverest/user-registration, pull requests merged in 2023-12, with the labels that each got.

#631 UR-1235 Enhance - Display payment status in detailed.
  assets/js/frontend/user-registration.js
Labels: enhancement, Approved, Merged, Tested

#623 UR-1045 Feature - Form Locate.
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-registrations-table-list.php
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Merged, Tested

#630 Enhance - UR-1096 Length Feature Input and Textarea.
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration-form-validator.js
  includes/abstracts/abstract-ur-form-field.php
  includes/class-ur-frontend-scripts.php
  includes/form/class-ur-form-field-text.php
  includes/form/class-ur-form-field-textarea.php
  includes/form/settings/class-ur-setting-text.php
  includes/form/settings/class-ur-setting-textarea.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  includes/validation/class-ur-validation.php
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Approved, Merged, Tested, Needs Documentation

#632 Feature - Slot booking
  assets/js/admin/form-builder.js
  includes/abstracts/abstract-ur-form-field.php
  includes/functions-ur-template.php
  includes/validation/class-ur-form-validation.php
  templates/myaccount/form-edit-profile.php
Labels: Approved, Ready to Merge, dependencies, Tested, Needs Documentation

#633 UR-1091 Refactor -Remove payments addon dependency form stripe.
  includes/admin/class-ur-admin-menus.php
Labels: Needs Review, Needs Tests, Type: Refactor

#639 UR-1306 Tweak - Parse approval link smart tag properly
  includes/class-ur-emailer.php
  includes/class-ur-smart-tags.php
Labels: enhancement, Approved, Merged, Tested

#641 UR-1238 Tweak - Manual user counting replaced with SQL query
  includes/admin/functions-ur-admin.php
Labels: enhancement, Needs Review, Needs Tests

#640 UR-1286 Tweak - Pending users meta query optimization
  includes/admin/class-ur-admin-user-list-manager.php
Labels: enhancement, Needs Review, Needs Tests

#636 Fix - Welcome email sent when profile details updated by admin
  includes/admin/class-ur-admin-user-list-manager.php
Labels: bug, Approved, Tested

#637 UR-1296 Fix - Support decimal value in number field
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration-form-validator.js
  includes/validation/class-ur-form-validation.php
Labels: Approved, Ready to Merge, Tested

#642 UR-1240 Lost password page redirecting to login page.
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: bug, Ready to Merge, Tested

#638 UR-1304 Fix - Send email change confirmation with templates
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
Labels: bug, Approved, Ready to Merge, Tested

#644 UR-1276 Tweak - Default form fields arrangement
  includes/class-ur-form-handler.php
  includes/class-ur-install.php
Labels: enhancement, Approved, Ready to Merge, Tested

#643 UR-1307 Fix - Profile completeness hook mismatch issue
  templates/myaccount/form-edit-profile.php
Labels: Approved, Type: Refactor, Ready to Merge, Tested

#645 UR-1302 Enhance - Smart tags parseable endpoint content
  includes/class-ur-smart-tags.php
  includes/functions-ur-core.php
  templates/myaccount/dashboard.php
Labels: enhancement, Approved, Ready to Merge, Tested

#634 Fix - Placeholder is not working in the country field
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-assets.php
  includes/form/class-ur-form-field-country.php
  includes/form/settings/class-ur-setting-country.php
  includes/functions-ur-template.php
Labels: bug, Approved, Ready to Merge, Tested

#635 Fix - Select field option not changing instantly
  assets/js/admin/form-builder.js
Labels: bug, Approved, Ready to Merge, Tested
