Repository wpeverest/user-registration, pull requests merged in 2023-06, with the labels that each got.

#561 UR-930 Enhance - Add new addons to extensions page
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/klaviyo.png
  assets/extensions-json/sections/images/post-submission.png
  assets/extensions-json/sections/images/profile-completeness.png
  assets/extensions-json/sections/images/save-and-continue.png
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#562 UR-929 Refactor - Create global constant for upload dir path and url
  includes/class-ur-ajax.php
  includes/class-ur-install.php
  includes/functions-ur-core.php
  user-registration.php
Labels: bug, Approved, Merged, Tested

#564 Fix - Missing user id in export user
  includes/admin/class-ur-admin-export-users.php
Labels: bug, Approved, Merged, Tested

#567 Tweak - Filter added for recaptcha url.
  includes/class-ur-form-handler.php
Labels: bug

#571 UR-980 Fix - Form design conflict with themes using bootstrap
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
Labels: bug, Approved, Merged, Tested

#570 UR-978 Enhance - One time draggable field locked message
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-assets.php
Labels: enhancement, Approved, Merged, Tested

#569 Tweak - Allow search engine indexing wont turn off
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#572 UR-946 Fix -Max upload size option accepting non-numeric, negative, and 0 as values
  assets/js/admin/form-builder.js
Labels: bug, Approved, Merged, Tested

#573 Fix - Required validation when entering 0 in number field
  includes/validation/class-ur-validation.php
Labels: bug, Approved, Merged, Tested

#566 UR-975 Tweak - Password strength meter hint text
  assets/js/frontend/password-strength-meter.js
  includes/admin/class-ur-admin-assets.php
  includes/class-ur-frontend-scripts.php
Labels: enhancement, Approved, Merged, Tested

#565 UR-972 Tweak - Redirection for autologin registration
  includes/functions-ur-template.php
Labels: enhancement, Approved, Merged, Tested

#575 Fix - Validation error when range is used as payment field
  includes/class-ur-ajax.php
  includes/functions-ur-template.php
Labels: bug, Approved, Merged, Tested

#568 UR-910 Tweak - UR 3.0 feedback design changes
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/components/_card.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/deactivation-feedback-rtl.css
  assets/css/deactivation-feedback.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/settings-rtl.css
  assets/css/settings.css
  assets/css/settings.scss
  assets/css/ur-notice-rtl.css
  assets/css/ur-notice.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/variables/_colors.scss
  assets/js/admin/admin.js
  includes/admin/settings/class-ur-settings-email.php
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Merged, Tested

#574 Fix - Vulnerability issue to arbitrary file upload
  includes/abstracts/abstract-ur-session.php
  includes/admin/class-ur-admin-import-export-forms.php
  includes/admin/functions-ur-admin.php
  includes/admin/updater/class-ur-addon-updater.php
  includes/class-ur-ajax.php
  includes/class-ur-session-handler.php
  includes/functions-ur-core.php
  templates/form-registration.php
Labels: bug, Impact: High, Approved, Merged, Tested
