Repository wpeverest/user-registration, pull requests merged in 2023-04, with the labels that each got.

#542 Enhancement - Checkbox setting replaced with toggle.
  assets/css/settings-rtl.css
  assets/css/settings.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-integration.php
  includes/admin/settings/class-ur-settings-misc.php
  includes/admin/settings/emails/class-ur-settings-admin-email.php
  includes/form/class-ur-form-field-date.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#540 UR-736 Fix - Profile picture not recognized by media library
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#547 Enhancement - Lock disable field if integration not setup
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
Labels: enhancement, Approved, Merged, Tested

#538 Tweak - Incorrect default date displayed in date field while editing the user
  includes/admin/class-ur-admin-profile.php
Labels: enhancement, Approved, Merged, Tested

#525 Enhancement - List of smart tags in email content
  assets/js/admin/form-builder.js
  assets/js/admin/form-modal.js
  includes/abstracts/abstract-ur-field-settings.php
  includes/admin/class-ur-admin-form-modal.php
  includes/class-ur-emailer.php
  includes/class-ur-shortcodes.php
  includes/class-ur-smart-tags.php
  user-registration.php
Labels: enhancement, Approved, Merged, Tested, Needs Documentation

#543 Enhancement - Upgrade to pro link
  includes/admin/class-ur-admin-menus.php
Labels: enhancement, Approved, Merged, Tested

#520 Enhancement - Export users
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-export-users.php
  includes/admin/views/html-admin-page-export-users.php
Labels: enhancement, Approved, Merged, Tested, compatibility

#524 Enhancement - Form field shows upgrade to premium notice
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/ur-setup.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-form-templates.php
  includes/admin/class-ur-admin-menus.php
  includes/class-ur-ajax.php
  includes/class-ur-plugin-updater.php
Labels: enhancement, Approved, Merged, Tested
