Repository wpeverest/user-registration, pull requests merged in 2024-04, with the labels that each got.

#697 UR-1430 Enhancement - Screenshot video on upgrade to pro popup.
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-menus.php
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Merged, Tested

#696 UR 1462 Fix - Denied is not working when email confirmation is enabled.
  includes/admin/class-ur-admin-user-manager.php
  includes/class-ur-user-approval.php
Labels: bug, Approved, Ready to Merge

#695 UR-1020 Fix - Woocommerce my account edit profile sync.
  includes/frontend/class-ur-frontend-form-handler.php
Labels: bug, Approved, Merged, Tested

#694 Added - Dev Compatibility for Subscription Plan trail period.
  assets/js/admin/form-builder.js
Labels: enhancement, Approved, Merged, Tested

#692 UR-1273 Feature - Added smart phone number in billing phone number.
  assets/js/frontend/user-registration.js
Labels: enhancement, Approved, Merged, Tested

#691 UR-1218 Fix- Avatar files are left behind after deleting user.
  includes/admin/class-ur-admin.php
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#686 Fix - Checkbox values are not being saved when there is a single option.
  assets/js/frontend/user-registration.js
Labels: bug, Approved, Ready to Merge, Tested

#684 UR-1423 Fix - Required Validation of Text Fields Issue (Input, First Name, Last Name, etc..).
  assets/js/frontend/jquery.validate.js
  assets/js/frontend/user-registration-form-validator.js
  includes/validation/class-ur-validation.php
Labels: bug, Approved, Ready to Merge, Tested

#683 UR-1408 Fix- PHP version 8.3 combability issue
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  includes/admin/settings/emails/class-ur-settings-admin-email.php
  includes/admin/settings/emails/class-ur-settings-approval-link-email.php
  includes/admin/settings/emails/class-ur-settings-awaiting-admin-approval-email.php
  includes/admin/settings/emails/class-ur-settings-confirm-email-address-change-email.php
  includes/admin/settings/emails/class-ur-settings-email-confirmation.php
  includes/admin/settings/emails/class-ur-settings-profile-details-changed-email.php
  includes/admin/settings/emails/class-ur-settings-profile-details-updated-email.php
  includes/admin/settings/emails/class-ur-settings-registration-approved-email.php
  includes/admin/settings/emails/class-ur-settings-registration-denied-email.php
  includes/admin/settings/emails/class-ur-settings-registration-pending-email.php
  includes/admin/settings/emails/class-ur-settings-reset-password-email.php
  includes/admin/settings/emails/class-ur-settings-successfully-registered-email.php
Labels: bug, Approved, Ready to Merge, Tested

#678 UR-1412 Fix Change the 'All UR Forms' filter name to 'All Users' at Users > All Users
  includes/admin/class-ur-admin-user-list-manager.php
Labels: enhancement, Approved, Ready to Merge, Tested

#674 UR-1359 Enhancement Text Area Enhancement
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
  includes/form/settings/class-ur-setting-textarea.php
  includes/form/views/admin/admin-textarea.php
  includes/functions-ur-template.php
Labels: enhancement, Approved, Ready to Merge, Tested

#671 UR-1361 Fix when no redirection the waiting period for redirection should be hidden
  assets/js/admin/admin.js
  user-registration.php
Labels: bug, Approved, Ready to Merge, Tested

#670 Fixed - My Account URL issue on custom permalink.
  includes/functions-ur-page.php
Labels: bug, Approved, Ready to Merge, Tested

#669 Tweak - Tooltip message for Username, Text and Textarea of Length Advance Settings.
  includes/form/settings/class-ur-setting-text.php
  includes/form/settings/class-ur-setting-textarea.php
  includes/form/settings/class-ur-setting-user_login.php
Labels: enhancement, Approved, Ready to Merge, Tested

#672 Feature - Automatic user login after email confirmation and reset password.
  includes/class-ur-email-confirmation.php
  includes/functions-ur-core.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: Approved, Feature Request, Ready to Merge, Tested

#667 UR-1343 Enhance - Send Bulk Resend Verification Email
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin-user-manager.php
  includes/class-ur-email-confirmation.php
  includes/class-ur-user-approval.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Ready to Merge, Tested

#682 UR-574 Fix -Tooltip is-removed when clicked multiple times on field-in builder
  assets/js/admin/admin.min.js
  assets/js/admin/form-builder.js
  assets/js/admin/form-builder.min.js
  assets/js/frontend/user-registration-form-validator.min.js
  assets/js/frontend/user-registration.js
  assets/js/frontend/user-registration.min.js
Labels: bug, Approved, Ready to Merge, Tested

#698 Dev - Module system Compatibility.
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin.php
  includes/class-ur-frontend-scripts.php
  includes/class-ur-plugin-updater.php
  includes/functions-ur-core.php
Labels: enhancement, Status: Needs Docs, Needs Review, Needs Tests

#688 Enhancement - User registration gutenberg blocks
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  assets/js/admin/gutenberg/form-block.js
  includes/RestApi/class-ur-rest-api.php
  includes/RestApi/controllers/version1/class-ur-addons.php
  includes/RestApi/controllers/version1/class-ur-changelog.php
  includes/RestApi/controllers/version1/class-ur-features.php
  includes/RestApi/controllers/version1/class-ur-gutenberg-blocks.php
  includes/admin/class-ur-admin-dashboard.php
  includes/admin/class-ur-admin-welcome.php
  includes/blocks/block-types/class-ur-block-abstract.php
  includes/blocks/block-types/class-ur-block-edit-password.php
  includes/blocks/block-types/class-ur-block-edit-profile.php
  includes/blocks/block-types/class-ur-block-login-form.php
  includes/blocks/block-types/class-ur-block-myaccount.php
  includes/blocks/block-types/class-ur-block-registration-form.php
  includes/blocks/class-ur-blocks.php
  includes/class-ur-form-block.php
  includes/functions-ur-template.php
  package-lock.json
  package.json
  src/blocks/blocks/edit-password/Edit.js
  src/blocks/blocks/edit-password/Save.js
  src/blocks/blocks/edit-password/block.json
  src/blocks/blocks/edit-password/index.js
  src/blocks/blocks/edit-profile/Edit.js
  src/blocks/blocks/edit-profile/Save.js
  src/blocks/blocks/edit-profile/block.json
  src/blocks/blocks/edit-profile/index.js
  src/blocks/blocks/index.js
  src/blocks/blocks/login-form/Edit.js
  src/blocks/blocks/login-form/Save.js
  src/blocks/blocks/login-form/block.json
  src/blocks/blocks/login-form/index.js
  src/blocks/blocks/myaccount/Edit.js
  src/blocks/blocks/myaccount/Save.js
  src/blocks/blocks/myaccount/block.json
  src/blocks/blocks/myaccount/index.js
  src/blocks/blocks/registration-form/Edit.js
  src/blocks/blocks/registration-form/Save.js
  src/blocks/blocks/registration-form/block.json
  src/blocks/blocks/registration-form/index.js
  src/blocks/components/Icon.js
  src/blocks/components/hoc/index.js
  src/blocks/components/hoc/withChakraUIProvider.js
  src/blocks/editor.scss
  src/blocks/index.js
  src/blocks/style.scss
  src/dashboard/screens/Modules/Addons/Addons.js
  src/dashboard/screens/Modules/Addons/addons-api.js
  src/dashboard/screens/Modules/Addons/components/AddonItem.js
  src/dashboard/screens/Modules/Features/Features.js
  src/dashboard/screens/Modules/Features/components/FeatureItem.js
  src/dashboard/screens/Modules/Features/features-api.js
  user-registration.php
  webpack.config.js
Labels: enhancement, Approved, Status: Needs Design, Type: Refactor, Ready to Merge, Tested, Needs Documentation

#668 Added - Dev Compatibility for Checkout Page frontend validation.
  assets/js/frontend/user-registration-form-validator.js
  includes/form/class-ur-form-field-text.php
  includes/form/class-ur-form-field-textarea.php
Labels: bug, Approved, Tested

#701 Fix - Required Field error message for conditionally hidden fields.
  assets/js/frontend/user-registration-form-validator.js
Labels: bug, Approved, Merged, Tested

#700 Fix - Form doesn't work when File Upload is required.
  includes/form/class-ur-form-field-number.php
  includes/validation/class-ur-validation.php
Labels: bug, Approved, Merged, Tested
