Repository wpeverest/user-registration, pull requests merged in 2024-09, with the labels that each got.

#744 UR- 960 Enhance - Support relative URL
  includes/validation/class-ur-setting-validation.php
  includes/validation/class-ur-validation.php
  templates/myaccount/form-login.php
Labels: enhancement, Approved, Ready to Merge, Tested

#745 UR-1434 Enhancement - Show most used integration list on integration tab
  assets/css/settings.scss
  assets/images/settings-icons/sms_integration.png
  assets/js/admin/admin.js
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-integration.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#747 UR 1071 Dev -Elementor widget
  assets/css/admin.scss
  assets/fonts/UserRegistration.eot
  assets/fonts/UserRegistration.svg
  assets/fonts/UserRegistration.ttf
  assets/fonts/UserRegistration.woff
  includes/3rd-party/elementor/class-ur-elementor.php
  includes/3rd-party/elementor/widgets/class-ur-widgets-edit-password.php
  includes/3rd-party/elementor/widgets/class-ur-widgets-edit-profile.php
  includes/3rd-party/elementor/widgets/class-ur-widgets-login.php
  includes/3rd-party/elementor/widgets/class-ur-widgets-myaccount.php
  includes/3rd-party/elementor/widgets/class-ur-widgets-popup.php
  includes/3rd-party/elementor/widgets/class-ur-widgets-profile-details.php
  includes/3rd-party/elementor/widgets/class-ur-widgets-registration.php
  templates/myaccount/my-account.php
Labels: Approved, Feature Request, Merged, Tested

#749 Fix - Issue in saving shipping address different to billing in woocommerce
  assets/js/frontend/user-registration.js
Labels: bug, Needs Review, Needs Tests

#750 Enhance - Warning for field deletion used in Conditional Logic
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-assets.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#751 UR-1756 Dev - Handle common functions and dynamic links for custom notices.
  includes/admin/functions-ur-admin.php
  includes/admin/notifications/class-ur-admin-notices.php
Labels: enhancement, Approved, Ready to Merge, Tested

#746 UR-1680 Enhance - Dashboard Page
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/extensions-json/all-features.json
  assets/extensions-json/sections/all_extensions.json
  includes/RestApi/controllers/version1/class-ur-modules.php
  includes/class-ur-smart-tags.php
  package-lock.json
  package.json
  src/blocks/components/Icon.js
  src/dashboard/components/Header/Header.js
  src/dashboard/components/Icon/Icon.js
  src/dashboard/components/Theme/Theme.js
  src/dashboard/screens/Help/Lists/ShortcodesLists/ShortcodesLists.js
  src/dashboard/screens/Modules/Modules.js
  src/dashboard/screens/Modules/components/ModuleBody.js
  src/dashboard/screens/Modules/components/ModuleItem.js
  src/dashboard/screens/Modules/components/modules-api.js
Labels: enhancement, Approved, Merged, Tested

#755 Feature - MailPoet Integration
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/mailpoet.png
  assets/images/settings-icons/mailpoet.png
  includes/functions-ur-core.php
Labels: Approved, Feature Request, Ready to Merge, Tested

#753 UR-1575 Fix - Removed userstate from attributes.
  includes/shortcodes/class-ur-shortcode-login.php
  src/blocks/blocks/login-form/Edit.js
  src/blocks/blocks/myaccount/Edit.js
Labels: bug, Approved, Merged

#756 UR-1679 Feature - WPBakery compatibility with user registration widgets.
  assets/css/activation.scss
  includes/functions-ur-core.php
Labels: Approved, Feature Request, Merged, Tested, Needs Documentation
