Repository wpeverest/user-registration, pull requests merged in 2024-07, with the labels that each got.

#719 Fix - page_id, page_url, page_title smart tags not working on certain emails.
  includes/class-ur-smart-tags.php
Labels: bug, Approved, Merged, Tested

#709 UR-874 Dev - Compatibility for not being able to delete password field even if auto password generation is enabled.
  assets/js/admin/form-builder.js
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Ready to Merge, Tested

#710 UR-1458 Dev - Compatibility for payment disabled message
  assets/js/admin/form-builder.js
Labels: bug, Approved, Ready to Merge, Tested

#714 UR-1564 Fix - Avoid multiple query for the same info
  includes/class-ur-form-handler.php
  includes/functions-ur-core.php
  includes/functions-ur-page.php
Labels: bug, Approved, Ready to Merge, Tested

#716 UR-1483 Feature - Akismet integration
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.js
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
Labels: Approved, Feature Request, Ready to Merge, Tested

#720 UR -1552 Optimization -Script and styles optimization.
  includes/admin/class-ur-admin-assets.php
  includes/admin/functions-ur-admin.php
  includes/class-ur-frontend-scripts.php
Labels: enhancement, Approved, Merged, Tested

#708 UR-687 Dev - Compatibility for Signature Field
  assets/css/_fonts.scss
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/variables/_colors.scss
  assets/fonts/UserRegistration.eot
  assets/fonts/UserRegistration.svg
  assets/fonts/UserRegistration.ttf
  assets/fonts/UserRegistration.woff
  includes/admin/class-ur-admin-profile.php
  includes/functions-ur-core.php
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Approved, Ready to Merge, Tested

#712 UR-1491 Dev - Compatibility temporarily disable users.
  assets/css/admin.scss
  includes/class-ur-user-approval.php
  includes/functions-ur-core.php
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: Approved, Tested

#718 UR-851 Dev - Compatibility for feature request set exact date for subscription to end.
  assets/js/admin/form-builder.js
  includes/abstracts/abstract-ur-form-field.php
Labels: Feature Request

#723 Dev - Compatibility for Image based Captcha
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
  includes/abstracts/abstract-ur-form-field.php
Labels: Approved, Merged, Tested, compatibility

#722 UR-1618 Refactor - Custom notice conditionally rendering system.
  assets/js/admin/ur-notice.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-notices.php
  includes/admin/class-ur-admin.php
  includes/admin/functions-ur-admin.php
  includes/admin/notifications/class-ur-admin-notices.php
  includes/admin/notifications/views/html-notice-banner.php
  includes/admin/notifications/views/html-notice-custom.php
  includes/admin/notifications/views/html-notice-deactivation.php
  includes/admin/notifications/views/html-notice-error.php
  includes/admin/notifications/views/html-notice-install.php
  includes/admin/notifications/views/html-notice-key-activated.php
  includes/admin/notifications/views/html-notice-key-deactivated.php
  includes/admin/notifications/views/html-notice-key-unvalidated.php
  includes/admin/notifications/views/html-notice-php-deprecation.php
  includes/admin/notifications/views/html-notice-registration.php
  includes/admin/notifications/views/html-notice-update.php
  includes/admin/notifications/views/html-notice-updated.php
  includes/admin/notifications/views/html-notice-updating.php
  includes/class-ur-ajax.php
  includes/class-ur-install.php
  includes/class-ur-plugin-updater.php
  includes/functions-ur-core.php
Labels: Approved, Type: Refactor, Ready to Merge, Tested

#721 UR-1490 Dev - Compatibility with Repeater Fields Addon
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/extensions-json/all-features.json
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/repeater-fields.png
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration-form-validator.js
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-profile.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/class-ur-shortcodes.php
  includes/form/class-ur-form-field-checkbox.php
  includes/form/class-ur-form-field-country.php
  includes/form/class-ur-form-field-date.php
  includes/form/class-ur-form-field-number.php
  includes/form/class-ur-form-field-password.php
  includes/form/class-ur-form-field-radio.php
  includes/form/class-ur-form-field-text.php
  includes/form/class-ur-form-field-textarea.php
  includes/form/class-ur-form-field-user-email.php
  includes/form/class-ur-form-field-user-login.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
  includes/functions-ur-form.php
  includes/functions-ur-template.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  includes/validation/class-ur-form-validation.php
  includes/validation/class-ur-setting-validation.php
  templates/form-registration.php
  templates/myaccount/form-edit-profile.php
Labels: Approved, Feature Request, Ready to Merge, Tested
