Repository wpeverest/user-registration, pull requests merged in 2024-11, with the labels that each got.

#766 UR-1777 Enhance - My account page design
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/my-account-layout.scss
  assets/css/variables/_structure.scss
  assets/js/frontend/my-account.js
  includes/class-ur-frontend-scripts.php
  includes/class-ur-smart-tags.php
  includes/functions-ur-account.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  templates/myaccount/dashboard.php
  templates/myaccount/form-edit-password.php
  templates/myaccount/form-edit-profile.php
  templates/myaccount/navigation.php
Labels: enhancement, Approved, Merged, Tested

#765 UR-1686 Enhance - Email marketing integration menu in form settings
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/images/no-integration-selected.png
  assets/images/settings-icons/zapier.png
  assets/js/admin/admin.js
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Needs Review, Needs Tests, Merged

#767 Fix - Hide Unapproved Users action run for users not from our source
  assets/js/frontend/user-registration.js
  includes/class-ur-user-approval.php
Labels: bug, Approved, Needs Review, Needs Tests, Merged

#771 Fix - Form save action not working for initial form publish captcha setting
  includes/class-ur-ajax.php
  includes/functions-ur-core.php
Labels: bug, Approved, Ready to Merge, Merged, Tested

#769 UR 1879 Bug - Fix for random order in email of form inputs during user registration
  includes/frontend/class-ur-frontend-form-handler.php
  includes/validation/class-ur-form-validation.php
Labels: bug, Approved, Merged

#770 UR-1864 Dev - Page builder compatibility oxygen
  assets/css/user-registration.scss
  includes/3rd-party/oxygen/class-ur-oxygen.php
  includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-editpassword.php
  includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-editprofile.php
  includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-login.php
  includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-myaccount.php
  includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-popup.php
  includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-profile-details.php
  includes/3rd-party/oxygen/widgets/class-ur-oxygen-widget-registration.php
  includes/3rd-party/oxygen/widgets/class-ur-oxygen-widgets.php
  user-registration.php
Labels: Approved, Feature Request, Merged, Tested

#772 Compatibility - ConvertKit Addon
  assets/extensions-json/sections/all_extensions.json
  assets/images/settings-icons/convertkit.png
Labels: Needs Review, Needs Tests, Feature Request, Needs Documentation
