Repository wpeverest/user-registration, pull requests merged in 2024-08, with the labels that each got.

#724 UR-1693 Fix - The email content translation issues with WPML plugin.
  assets/js/frontend/user-registration.js
  includes/class-ur-emailer.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
  templates/form-registration.php
Labels: bug, Approved, Merged, Tested

#725 UR-1605 Fix - Disable default wordpress login not working.
  includes/admin/class-ur-admin-settings.php
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#726 Dependency for login block
  includes/blocks/block-types/class-ur-block-login-form.php
  includes/blocks/block-types/class-ur-block-myaccount.php
  includes/blocks/block-types/class-ur-block-registration-form.php
  includes/class-ur-shortcodes.php
  includes/shortcodes/class-ur-shortcode-login.php
  src/blocks/blocks/login-form/Edit.js
  src/blocks/blocks/login-form/block.json
  src/blocks/blocks/myaccount/Edit.js
  src/blocks/blocks/myaccount/block.json
  src/blocks/blocks/registration-form/Edit.js
  src/blocks/blocks/registration-form/block.json
Labels: enhancement, Approved, Merged, Tested

#727 UR-1658 Fix - Anyone can register option not working due to conflict with Really Simple SSL plugin
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#728 UR-1595 Feature- Embed option in form builder
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/images/icons/red-arrow.svg
  assets/js/admin/form-builder.js
  assets/js/admin/shortcode-form-embed.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-embed-wizard.php
  includes/admin/views/html-admin-page-forms.php
  includes/blocks/class-ur-blocks.php
  includes/class-ur-ajax.php
  user-registration.php
Labels: Approved, Feature Request, Merged, Tested

#730 UR-1656 Tweak - Catch mail send error
  includes/admin/class-ur-admin-assets.php
  includes/admin/notifications/views/html-notice-banner.php
  includes/admin/settings/class-ur-settings-email.php
  includes/class-ur-ajax.php
  includes/class-ur-emailer.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#731 UR-1444 Enhance - Profile picture sync with registration form
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-general.php
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Merged, Tested

#732 UR-1660 Tweak - Display ajax error on form save, submit, login and profile edit if ajax somehow has been disabled
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  assets/js/frontend/ur-login.js
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-assets.php
  includes/class-ur-frontend-scripts.php
Labels: enhancement, Approved, Merged

#733 UR-1566 Text Consistency.
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#734 Ur 1054 Enhancement - Custom password and Realtime password strength guide
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  assets/js/frontend/password-strength-meter.js
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-assets.php
  includes/class-ur-frontend-scripts.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#735 UR-1657 Enhance - Display notice about possible spam registrations if source different from our plugin's form
  assets/css/ur-notice-rtl.css
  assets/css/ur-notice.css
  assets/css/ur-notice.scss
  assets/js/admin/shortcode-form-embed.min.js
  includes/admin/class-ur-admin-assets.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged

#736 UR-1659 Feature - Elementor Widget for Registration Forms
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  includes/3rd-party/elementor/class-ur-elementor.php
  includes/3rd-party/elementor/class-ur-widget.php
  user-registration.php
Labels: Approved, Feature Request, Merged, Tested

#737 UR-1676 Dev - Add noreferer and noopener in all target blank anchor tags.
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-deactivation-feedback.php
  includes/admin/class-ur-admin-registrations-table-list.php
  includes/admin/class-ur-admin.php
  includes/admin/functions-ur-admin.php
  includes/admin/notifications/class-ur-admin-notices.php
  includes/admin/notifications/views/html-notice-deactivation.php
  includes/admin/notifications/views/html-notice-php-deprecation.php
  includes/admin/notifications/views/html-notice-registration.php
  includes/admin/settings/class-ur-settings-captcha.php
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-license.php
  includes/admin/settings/class-ur-settings-misc.php
  includes/admin/updater/class-ur-addon-updater.php
  includes/admin/views/html-admin-page-form-templates.php
  includes/admin/views/html-admin-page-forms.php
  includes/admin/views/html-login-page-forms.php
  includes/class-ur-ajax.php
  includes/class-ur-plugin-updater.php
  includes/class-ur-smart-tags.php
  includes/functions-ur-core.php
Labels: bug, Approved, Merged

#739 UR-1591 Tweak - Onboarding texts and buttons improvement
  includes/RestApi/controllers/version1/class-ur-getting-started.php
  includes/admin/class-ur-admin-welcome.php
  includes/admin/settings/class-ur-settings-misc.php
  src/context/gettingStartedContext.js
  src/welcome/components/App.js
  src/welcome/components/common/ConsentModal.js
Labels: enhancement, Approved, Merged, Tested

#741 Dev - Compatibility for Authorize.net Addon
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  assets/css/_fonts.scss
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/authorize-net.png
  assets/fonts/UserRegistration.eot
  assets/fonts/UserRegistration.svg
  assets/fonts/UserRegistration.ttf
  assets/fonts/UserRegistration.woff
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
  includes/admin/class-ur-admin-assets.php
  includes/functions-ur-core.php
  includes/validation/class-ur-form-validation.php
Labels: Approved, Feature Request, Merged, Tested, Needs Documentation

#742 UR-463 Dev - Compatibility for SMS Verification with Twilio Integration
  assets/extensions-json/all-features.json
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-user-manager.php
  includes/functions-ur-core.php
Labels: Approved, Feature Request, Merged, Tested
