Repository wpeverest/user-registration, pull requests merged in 2024-12, with the labels that each got.

#779 Fix - Slug translation issue on my account links
  includes/class-ur-smart-tags.php
Labels: bug, Approved, Merged, Tested

#775 UR - 1590 Feature -Force user logout on password change
  includes/class-ur-form-handler.php
Labels: Approved, Feature Request, Merged, Tested

#776 Fix - Form Builder RTL layout design issue.
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  languages/user-registration.pot
Labels: bug, Approved, Ready to Merge, Tested

#783 Fix - Username accepting some special characters
  assets/js/frontend/user-registration-form-validator.js
  includes/form/class-ur-form-field-user-login.php
  includes/form/settings/class-ur-setting-user_login.php
Labels: bug, Needs Review, Needs Tests

#784 Fix - Error handling when wp_insert_user throws error.
  includes/frontend/class-ur-frontend-form-handler.php
Labels: bug, Needs Review, Needs Tests

#780 Added - Check for UR my account and login in custom template.
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#789 Fix - Email content mismatch on Verified Email
  includes/class-ur-preview.php
Labels: bug, Approved, Merged, Tested

#778 UR-1519 Bug - Issue while making WYSWYG required
  assets/js/frontend/user-registration.js
Labels: bug, Approved, Merged, Tested

#785 Added - Hook before automatic user login after email confirmation
  includes/class-ur-email-confirmation.php
Labels: bug, Approved, Merged, Tested

#788 UR-1974 Bug - Undefined issue on custom password
  assets/js/frontend/password-strength-meter.js
  assets/js/frontend/user-registration.js
  includes/class-ur-frontend-scripts.php
Labels: bug, Needs Review

#781 Fix - Status changed to pending mail on registration.
  includes/class-ur-emailer.php
Labels: enhancement, Needs Review, Needs Tests

#782 UR-1920 Enhancement - Send active modules count like addons in tg tracking
  includes/RestApi/controllers/version1/class-ur-modules.php
  includes/stats/class-ur-stats.php
Labels: enhancement, Needs Review, Needs Tests

#791 Tweak - Design tweak for Login and Registration Form Frontend.
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/deactivation-feedback-rtl.css
  assets/css/deactivation-feedback.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/settings-rtl.css
  assets/css/settings.css
  assets/css/ur-notice-rtl.css
  assets/css/ur-notice.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/images/success.svg
  assets/js/admin/login-settings.js
  assets/js/admin/login-settings.min.js
  assets/js/frontend/ur-login.js
  assets/js/frontend/ur-login.min.js
  assets/js/frontend/user-registration.js
  assets/js/frontend/user-registration.min.js
  includes/admin/class-ur-admin-menus.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-page.php
  includes/admin/views/html-login-page-forms.php
  includes/class-ur-shortcodes.php
  includes/frontend/class-ur-frontend.php
  includes/functions-ur-core.php
  includes/functions-ur-notice.php
  languages/user-registration.pot
  templates/form-login-registration.php
  templates/form-registration.php
  templates/myaccount/form-login.php
  templates/myaccount/form-lost-password.php
  templates/myaccount/lost-password-confirmation.php
  templates/notices/error.php
Labels: enhancement, Approved, Merged, Tested

#787 Enhance - Login Form Builder and Settings
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/images/success.svg
  assets/js/admin/login-settings.js
  assets/js/admin/login-settings.min.js
  assets/js/admin/settings.js
  assets/js/admin/settings.min.js
  assets/js/frontend/ur-login.js
  assets/js/frontend/ur-login.min.js
  assets/js/frontend/user-registration.js
  assets/js/frontend/user-registration.min.js
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-registrations-table-list.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/functions-ur-admin.php
  includes/admin/settings/class-ur-settings-general.php
  includes/admin/settings/class-ur-settings-page.php
  includes/admin/views/html-login-page-forms.php
  includes/class-ur-ajax.php
  includes/class-ur-preview.php
  includes/class-ur-shortcodes.php
  includes/frontend/class-ur-frontend.php
  includes/functions-ur-core.php
  includes/functions-ur-notice.php
  includes/shortcodes/class-ur-shortcode-login.php
  languages/user-registration.pot
  templates/form-login-registration.php
  templates/form-registration.php
  templates/myaccount/form-login.php
  templates/myaccount/form-lost-password.php
  templates/myaccount/lost-password-confirmation.php
  templates/notices/error.php
Labels: enhancement, Approved, Merged, Tested
