Repository wpeverest/user-registration, pull requests merged in 2024-10, with the labels that each got.

#752 Ur-1678 Feature - User edit feature for admin. (Sync)
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  includes/validation/class-ur-form-validation.php
Labels: Approved, Feature Request, Ready to Merge, Tested

#763 UR-1825 Tweak - My account selection validation and install pages
  assets/js/admin/settings.js
  includes/RestApi/controllers/version1/class-ur-getting-started.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/class-ur-admin-welcome.php
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-ajax.php
  includes/class-ur-install.php
  includes/functions-ur-core.php
  src/context/gettingStartedContext.js
  src/welcome/components/App.js
  src/welcome/components/screens/InstallPage.js
Labels: enhancement, Approved, Ready to Merge, Tested

#758 UR-1691 Dev - Compatibility for Conditional logic in row
  assets/css/admin.scss
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-menus.php
  includes/class-ur-ajax.php
  templates/form-registration.php
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Needs Review, Needs Tests

#762 Enhance - Seperate Captcha Settings for Login and Registration Form
  assets/css/settings.scss
  assets/images/settings-icons/cloudflare.png
  assets/images/settings-icons/hCaptcha.png
  assets/images/settings-icons/v2.png
  assets/images/settings-icons/v3.png
  assets/js/admin/form-settings.js
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-captcha.php
  includes/admin/settings/class-ur-settings-general.php
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/class-ur-frontend-scripts.php
  includes/class-ur-shortcodes.php
  includes/functions-ur-core.php
  includes/stats/class-ur-stats.php
Labels: enhancement, Approved, Tested, Needs Documentation
