Repository wpeverest/user-registration, pull requests merged in 2024-05, with the labels that each got.

#702 UR-1499 Fix - Enquing style and script only to UR screens.
  includes/admin/class-ur-admin-assets.php
Labels: bug, Approved, Merged, Tested

#704 UR-977 Enhance - Smart tags picker design
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  assets/js/admin/form-modal.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-form-modal.php
  includes/class-ur-smart-tags.php
Labels: enhancement, Approved, Ready to Merge, Tested

#699 Sync changes with pro for qna verification type
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-assets.php
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Merged, Tested

#707 UR-1476 Enhance - All forms list table design
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-registrations-table-list.php
  includes/admin/views/html-login-page-forms.php
  includes/class-ur-form-handler.php
Labels: enhancement, Approved, Ready to Merge, Tested

#703 UR-1438 Enhance - Approval email process and email contents
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  assets/css/settings-rtl.css
  assets/css/settings.css
  assets/css/settings.scss
  assets/js/admin/admin.js
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/emails/class-ur-settings-admin-email.php
  includes/admin/settings/emails/class-ur-settings-approval-link-email.php
  includes/admin/settings/emails/class-ur-settings-profile-details-changed-email.php
  includes/class-ur-email-approval.php
  includes/class-ur-emailer.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#706 UR-1526 Enhance - WPML email translation with user selected language.
  includes/class-ur-emailer.php
  includes/functions-ur-core.php
Labels: bug, Needs Review, Needs Tests

#705 UR-1454 Dev -Dependency for google sheets
  assets/js/admin/form-builder.js
  includes/admin/class-ur-admin-assets.php
  includes/class-ur-email-confirmation.php
Labels: compatibility
