Repository wpeverest/user-registration, pull requests merged in 2024-02, with the labels that each got.

#661 Tweak - Code comments made more descriptive
  includes/functions-ur-template.php
  includes/interfaces/class-ur-log-handler-interface.php
  includes/shortcodes/class-ur-shortcode-login.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  includes/stats/class-ur-stats.php
Labels: Status: Needs Author Feedback, Needs Review, Needs Tests, Documented

#653 Feature - Deny Smart Tag in Admin Approval.
  includes/admin/class-ur-admin-user-manager.php
  includes/admin/settings/emails/class-ur-settings-approval-link-email.php
  includes/class-ur-email-approval.php
  includes/class-ur-emailer.php
  includes/class-ur-smart-tags.php
  includes/functions-ur-core.php
Labels: Approved, Feature Request, Ready to Merge, Tested, Needs Documentation

#647 Fix - Fields select 2 and multi select option not changing instantly in builder setting area
  assets/js/admin/form-builder.js
Labels: enhancement, Approved, Needs Review, Needs Tests, Ready to Merge, Tested

#648 Fix - Validation error while profile update if field visiblity is applied on fields.
  includes/validation/class-ur-form-validation.php
Labels: bug, Approved, Ready to Merge, Tested

#652 Tweak - Send user registration email template while sending reset password email from admin area
  includes/class-ur-emailer.php
Labels: enhancement, Approved, Ready to Merge, Tested

#657 Fix - Country Field default value none Frontend Issue.
  includes/form/class-ur-form-field-country.php
  includes/functions-ur-template.php
Labels: bug, Ready to Merge, Tested

#650 Fix - Remove extra password field value in mail
  includes/class-ur-emailer.php
Labels: enhancement, Ready to Merge, Tested

#660 Tweak - Introduce form name smart tag in user registration
  includes/class-ur-smart-tags.php
Labels: enhancement, Approved, Ready to Merge, Tested

#655 Tweak - Redirection back to previous page after registration
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: enhancement, Approved, Tested

#656 UR-1335 Tweak - From address going wrong in some emails
  includes/admin/settings/class-ur-settings-email.php
  includes/admin/settings/emails/class-ur-settings-confirm-email-address-change-email.php
  includes/class-ur-emailer.php
  includes/class-ur-form-handler.php
  includes/class-ur-smart-tags.php
Labels: enhancement, Approved, Ready to Merge, Tested

#665 UR-765 Feature - Trail Period for subscription.
  .distignore
  .github/sync-file-list.yml
  assets/css/_fonts.scss
  assets/css/admin.scss
  assets/css/my-account-layout.scss
  assets/css/user-registration.scss
  assets/fonts/UserRegistration.eot
  assets/fonts/UserRegistration.svg
  assets/fonts/UserRegistration.ttf
  assets/fonts/UserRegistration.woff
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-profile.php
  includes/class-ur-ajax.php
  templates/myaccount/form-edit-profile.php
Labels: Approved, Feature Request, Ready to Merge, Tested

#666 Feature - Introduction to {{passwordless_login_link}} Smart Tag.
  includes/admin/settings/class-ur-settings-email.php
  includes/class-ur-preview.php
  includes/class-ur-smart-tags.php
Labels: enhancement, Needs Review, Needs Extensive Test

#676 UR-1399 Fix - Escaping missing for display name.
  includes/class-ur-shortcodes.php
Labels: bug, Needs Review, Needs Tests

#677 UR-1389 Fix - Critical error while trying to login when using payment before login option
  includes/class-ur-user-approval.php
  includes/functions-ur-core.php
Labels: bug, Approved, Ready to Merge, Tested
