Repository wpeverest/user-registration, pull requests merged in 2025-05, with the labels that each got.

#858 Feature - Customize login form title and description.
  assets/js/admin/login-settings.js
  includes/functions-ur-core.php
  templates/myaccount/form-login.php
Labels: enhancement, Approved, Ready to Merge, Tested

#835 UR-2211 Fix - Remove unnecessary lost your password link from error message
  includes/functions-ur-account.php
Labels: bug, Approved, Needs Review, Needs Tests, Ready to Merge

#849 Fix - Password strength not working on edit profile and lost password page.
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  includes/shortcodes/class-ur-shortcode-my-account.php
Labels: bug, Approved, Ready to Merge, Tested

#855 Ur 2150 Enhance - Membership renewal reminder email.
  includes/Functions/CoreFunctions.php
  includes/admin/class-ur-admin-settings.php
  includes/class-ur-cron.php
  includes/class-ur-smart-tags.php
  includes/functions-ur-core.php
  modules/membership/includes/Admin.php
  modules/membership/includes/Admin/Repositories/MembersSubscriptionRepository.php
  modules/membership/includes/Admin/Services/EmailService.php
  modules/membership/includes/Admin/Services/SubscriptionService.php
  modules/membership/includes/Emails/EmailSettings.php
  modules/membership/includes/Emails/User/UR_Settings_Membership_Renewal_Reminder_User_Email.php
Labels: enhancement, Approved, Ready to Merge

#848 UR-1834 Feature - Add login/logout menu link for classical menu as well as block theme
  composer.lock
  includes/admin/class-ur-admin-menus.php
  includes/blocks/block-types/class-ur-block-login-form.php
  includes/blocks/block-types/class-ur-block-login-logout-menu.php
  includes/blocks/class-ur-blocks.php
  includes/functions-ur-account.php
  includes/menu-items/abstract-ur-nav-menu-item.php
  includes/menu-items/class-ur-login-logout-nav-menu-item.php
  src/blocks/blocks/index.js
  src/blocks/blocks/login-logout-menu/Edit.js
  src/blocks/blocks/login-logout-menu/block.json
  src/blocks/blocks/login-logout-menu/index.js
  src/blocks/components/Icon.js
  user-registration.php
Labels: Approved, Feature Request, Ready to Merge, Tested

#837 Enhancement - Content Restriction Block.
  assets/js/modules/content-restriction/admin/urcr-custom.js
  includes/RestApi/controllers/version1/class-ur-gutenberg-blocks.php
  includes/abstracts/abstract-ur-meta-boxes.php
  modules/content-restriction/admin/class-urcr-admin-meta-boxes.php
  modules/content-restriction/admin/settings/class-urcr-settings-file.php
  modules/content-restriction/class-urcr-shortcodes.php
  package-lock.json
  package.json
  src/blocks/blocks/content-restriction-enhanced/Edit.js
  src/blocks/blocks/content-restriction-enhanced/Save.js
  src/blocks/blocks/content-restriction-enhanced/block.json
  webpack.config.js
Labels: enhancement, Needs Review, Needs Tests, Needs Documentation

#854 UR-2342 Enhance - Setup Wizard Flow and Design
  Gruntfile.js
  assets/css/settings.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-setup-wizard.scss
  assets/css/user-registration.css
  assets/images/onboard-icons/onboarding-thumbnail.png
  includes/RestApi/controllers/version1/class-ur-getting-started.php
  includes/admin/class-ur-admin-welcome.php
  package-lock.json
  package.json
  src/dashboard/screens/Dashboard/Dashboard.js
  src/form-templates/App.js
  src/form-templates/components/TemplateList.js
  src/welcome/components/App.js
  src/welcome/components/Icon/Icon.js
  src/welcome/components/common/Header.js
  src/welcome/components/common/InputHandler.js
  src/welcome/components/screens/GeneralSettings.js
  src/welcome/components/screens/InstallPage.js
  src/welcome/components/screens/LastPage.js
  src/welcome/components/screens/RegistrationType.js
Labels: enhancement, Approved, Needs Review, Needs Tests, Ready to Merge

#856 Mollie Payment Gateway Integration
  assets/extensions-json/sections/all_extensions.json
  assets/extensions-json/sections/images/mollie.png
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration.js
  assets/js/modules/membership/admin/user-registration-membership-admin.js
  assets/js/modules/membership/frontend/user-registration-membership-frontend.js
  includes/admin/class-ur-admin-settings.php
  modules/membership/includes/AJAX.php
  modules/membership/includes/Admin.php
  modules/membership/includes/Admin/Services/MembershipService.php
  modules/membership/includes/Admin/Services/PaymentService.php
  modules/membership/includes/Admin/Services/SubscriptionService.php
  modules/membership/includes/Admin/Views/Partials/membership-admin-payments.php
  modules/membership/includes/Templates/membership-registration-form.php
  modules/payment-history/Orders.php
Labels: Approved, Needs Review, Needs Tests, Feature Request, Ready to Merge, Needs Extensive Test

#865 Tweak- Change twitter icon and background color for social login button.
  assets/css/variables/_colors.scss
Labels: enhancement, Needs Review, Needs Tests
