Repository wpeverest/user-registration, pull requests merged in 2025-06, with the labels that each got.

#867 UR-2495 Fix - Repeater fields values not being saved
  includes/class-ur-ajax.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/validation/class-ur-form-validation.php
Labels: bug, Approved, Ready to Merge

#875 UR-2533 Fix -Sstripe subscription invalid request.
  modules/membership/includes/AJAX.php
  modules/membership/includes/Admin/Services/Stripe/StripeService.php
Labels: bug, Approved, Tested

#868 Fix - All Fields smart tag not working on customize my account pages.
  includes/class-ur-smart-tags.php
Labels: bug, Needs Review, Needs Tests

#872 UR-2519 Fix - Form design issue
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  assets/css/user-registration.scss
Labels: bug, Needs Review, Needs Tests

#857 Fix - Opening the lightbox for long duration after login in admin dashboard.
  assets/js/admin/live-user-notice.js
Labels: bug, Approved, Ready to Merge, Tested

#860 Dev - Hook to modify user registration membership payment option label.
  modules/membership/includes/Templates/membership-registration-form.php
Labels: enhancement, Approved, Ready to Merge, Tested

#850 Fix - Textarea validation and character count message typo error.
  includes/functions-ur-template.php
  includes/validation/class-ur-validation.php
Labels: bug, Approved, Ready to Merge, Tested
