Repository wpeverest/user-registration, pull requests merged in 2025-02, with the labels that each got.

#777 UR-1264 Feature -Min max setting for default fields.
  CHANGELOG.txt
  assets/css/user-registration-default-frontend-rtl.css
  assets/css/user-registration-default-frontend.css
  assets/css/user-registration-default-frontend.scss
  assets/css/user-registration-form-preview.scss
  assets/css/user-registration-rtl.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  assets/js/admin/form-builder.js
  assets/js/frontend/user-registration-form-validator.js
  assets/js/frontend/user-registration-form-validator.min.js
  includes/Functions/CoreFunctions.php
  includes/admin/class-ur-admin-assets.php
  includes/form/class-ur-form-field-description.php
  includes/form/class-ur-form-field-display-name.php
  includes/form/class-ur-form-field-first-name.php
  includes/form/class-ur-form-field-last-name.php
  includes/form/class-ur-form-field-nickname.php
  includes/form/settings/class-ur-setting-description.php
  includes/form/settings/class-ur-setting-display_name.php
  includes/form/settings/class-ur-setting-first_name.php
  includes/form/settings/class-ur-setting-last_name.php
  includes/form/settings/class-ur-setting-nickname.php
  includes/functions-ur-core.php
  includes/shortcodes/class-ur-shortcode-login.php
  includes/shortcodes/class-ur-shortcode-my-account.php
  languages/user-registration.pot
  modules/membership/includes/Admin/Forms/class-ur-form-field-membership.php
  package-lock.json
  package.json
  readme.txt
  templates/myaccount/form-lost-password.php
  templates/myaccount/form-reset-password.php
  user-registration.php
Labels: Approved, Feature Request, Ready to Merge

#795 Tweak - SMS OTP message customization
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  includes/class-ur-smart-tags.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: enhancement, Needs Tests, Ready to Merge, Needs Documentation

#807 Fix - Strpos deprecated warning.
  includes/functions-ur-core.php
Labels: bug, Approved, Ready to Merge, Tested

#802 Tweak - Hook to modify checkbox validation message.
  assets/js/frontend/user-registration-form-validator.js
  includes/class-ur-frontend-scripts.php
Labels: enhancement, Approved, Ready to Merge, Tested

#799 Fix - File size upload in the edit profile according to server size.
  templates/myaccount/form-edit-profile.php
Labels: bug, Approved, Ready to Merge, Tested

#806 Fix- Stripslashes for the registration label in login form.
  templates/myaccount/form-login.php
Labels: bug, Approved, Ready to Merge, Tested

#798 Fix - Translation issue in text area field.
  includes/functions-ur-template.php
Labels: bug, Approved, Ready to Merge

#797 Fix - Email template for reset password from the admin dashboard.
  includes/class-ur-emailer.php
Labels: bug, Approved, Ready to Merge, Tested

#805 Fix - Popup for the customize my account on logout confirmation.
  assets/js/frontend/my-account.js
Labels: bug, Needs Review, Needs Tests

#794 Fix - 2FA otp page missing when using ur login shortcode in elementor shortcode.
  includes/shortcodes/class-ur-shortcode-login.php
Labels: bug, Approved, Ready to Merge, Tested

#803 Tweak - My account page popup trigger and trigger form modal popup.
  assets/js/frontend/user-registration.js
Labels: enhancement, Needs Review, Needs Tests

#808 Fix - Error message styling not changing from style customizer.
  assets/css/user-registration.scss
Labels: bug, Needs Review, Needs Tests

#796 Fix - Critical issue while exporting large amount of entries.
  includes/admin/class-ur-admin-export-users.php
Labels: bug, Needs Review, Needs Tests

#768 UR 1859 Feature - Compatibility changes free version for calculations
  assets/js/admin/form-builder.js
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: Needs Review

#809 Fix - User entries details on import export and on admin dashboard while using field visibility.
  includes/admin/class-ur-admin-export-users.php
  includes/admin/class-ur-admin-profile.php
Labels: bug, Needs Tests, Ready to Merge

#811 Enhance - Option to select lost password page.
  assets/js/admin/admin.js
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-settings.php
  includes/class-ur-ajax.php
  includes/functions-ur-account.php
  includes/functions-ur-core.php
Labels: enhancement, Needs Review, Needs Tests
