Repository wpeverest/user-registration, pull requests merged in 2025-07, with the labels that each got.

#882 Fix - Datetime field conflict with hello elementor theme.
  assets/js/frontend/user-registration.js
Labels: bug, Approved, Needs Tests, Ready to Merge

#878 Fix - Partial content restriction message Modification.
  modules/content-restriction/class-urcr-shortcodes.php
Labels: bug, Approved, Needs Tests, Merged

#891 UR 2545 Fix - Enable Paypal in form setting triggers override global paypal settings
  assets/js/admin/admin.js
Labels: bug, Approved, Needs Tests, Ready to Merge

#896 UR-2547 Fix - Failure of paypal form creation.
  includes/RestApi/controllers/version1/class-ur-plugin-status.php
Labels: bug, Approved, Needs Tests, Ready to Merge

#885 Ur-2379 Enhancement - Separate payment settings save mechanism for each payment module
  assets/images/settings-icons/authorize-net.png
  assets/images/settings-icons/bank.png
  modules/paypal/class-ur-paypal-module.php
Labels: enhancement, Approved, Needs Tests, Ready to Merge

#880 Fix - Default value exported instead of selected value in CSV.
  includes/admin/class-ur-admin-export-users.php
Labels: bug, Approved, Needs Review, Needs Tests, Ready to Merge

#881 Fix - Profile picture not exported in CSV file.
  includes/admin/class-ur-admin-export-users.php
Labels: bug, Approved, Ready to Merge

#898 UR 2361 Fix - Hidden hover css in login form submit button
  assets/css/user-registration.scss
  assets/js/admin/login-settings.js
  templates/myaccount/form-login.php
Labels: bug, Approved, Needs Tests, Ready to Merge

#894 UR-2578 - Fix Unable to check plugin status issue.
  includes/RestApi/controllers/version1/class-ur-plugin-status.php
  src/form-templates/components/PluginStatus.js
Labels: bug, Needs Review, Needs Tests

#897 UR 2622 Fix - Export users page issue in settings.
  includes/admin/views/html-admin-page-export-users.php
Labels: bug, Approved, Needs Tests, Ready to Merge

#879 Tweak - Redirection to respective payment settings.
  assets/extensions-json/all-features.json
  assets/extensions-json/sections/all_extensions.json
  modules/paypal/class-ur-paypal-module.php
Labels: enhancement, Approved, Needs Review, Needs Tests, Ready to Merge

#884 Fix - Submit button label and html content not translatable in WPML.
  includes/abstracts/abstract-ur-form-field.php
  wpml-config.xml
Labels: bug, Approved, Needs Tests, Ready to Merge
