Repository wpeverest/user-registration, pull requests merged in 2025-09, with the labels that each got.

#974 UR-3060 Fix - Currency position not working in payment
  assets/js/modules/membership/frontend/user-registration-membership-frontend.js
  includes/Functions/CoreFunctions.php
  modules/membership/includes/Frontend/Frontend.php
Labels: bug, Approved, Ready to Merge

#964 UR-3047 Fix - Inner page restriction message displayed even though override global setting is disabled
  modules/content-restriction/class-urcr-frontend.php
Labels: bug, Approved, Needs Review, Needs Tests, Ready to Merge

#958 UR-3039 Dev - Select stripe as the default gateway in membership registration
  assets/js/modules/membership/frontend/user-registration-membership-frontend.js
  modules/membership/includes/Frontend/Frontend.php
  modules/membership/includes/Templates/membership-registration-form.php
Labels: enhancement, Approved, Needs Review, Needs Tests, Ready to Merge

#977 UR-2643 Fix - Manage_user_registration capability not working for users tab in custom role
  includes/admin/settings/class-ur-users-list-table.php
  includes/admin/settings/class-ur-users-menu.php
Labels: bug, Approved, Needs Review, Needs Tests, Ready to Merge

#953 UR-2620 Enhance - Search filter in users table search
  includes/admin/settings/class-ur-users-list-table.php
Labels: enhancement, Approved, Ready to Merge

#982 UR-3057 Enhance - Persistent dismissal of non urm users admin notices in UR pages.
  assets/js/admin/ur-notice.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-user-list-manager.php
  includes/admin/class-ur-admin.php
  includes/admin/functions-ur-admin.php
  includes/class-ur-ajax.php
Labels: enhancement, Approved, Needs Review, Needs Tests, Ready to Merge

#987 UR-3046 Enhance - Rearrange settings for field options.
  UR-3046.diff
  assets/js/admin/admin.js
  assets/js/admin/form-builder.js
  includes/abstracts/abstract-ur-field-settings.php
  includes/abstracts/abstract-ur-form-field.php
  includes/admin/class-ur-admin.php
  includes/class-ur-ajax.php
  includes/form/settings/class-ur-setting-checkbox.php
  includes/form/settings/class-ur-setting-country.php
  includes/form/settings/class-ur-setting-date.php
  includes/form/settings/class-ur-setting-description.php
  includes/form/settings/class-ur-setting-display_name.php
  includes/form/settings/class-ur-setting-email.php
  includes/form/settings/class-ur-setting-first_name.php
  includes/form/settings/class-ur-setting-last_name.php
  includes/form/settings/class-ur-setting-nickname.php
  includes/form/settings/class-ur-setting-number.php
  includes/form/settings/class-ur-setting-password.php
  includes/form/settings/class-ur-setting-radio.php
  includes/form/settings/class-ur-setting-select.php
  includes/form/settings/class-ur-setting-text.php
  includes/form/settings/class-ur-setting-textarea.php
  includes/form/settings/class-ur-setting-user_confirm_email.php
  includes/form/settings/class-ur-setting-user_confirm_password.php
  includes/form/settings/class-ur-setting-user_email.php
  includes/form/settings/class-ur-setting-user_login.php
  includes/form/settings/class-ur-setting-user_pass.php
  includes/form/settings/class-ur-setting-user_url.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/frontend/class-ur-frontend.php
  includes/functions-ur-core.php
  modules/membership/includes/Admin/Forms/class-ur-form-field-membership.php
  templates/form-registration.php
Labels: enhancement, Needs Review, Needs Tests

#961 UR-2984 Enhance - Content restriction for membership status not active.
  modules/content-restriction/class-urcr-frontend.php
  modules/content-restriction/class-urcr-shortcodes.php
Labels: enhancement, Approved, Ready to Merge

#965 UR 2993 - Enhance - Individual hide label settings for login builder
  assets/css/admin.css
  assets/js/admin/login-settings.js
  includes/functions-ur-core.php
  templates/myaccount/form-login.php
Labels: enhancement, Approved, Ready to Merge

#962 UR-2827 Fix - Adeed backend validation for pg gateways.
  assets/js/modules/membership/admin/user-registration-membership-admin.js
  modules/membership/includes/Admin/Services/MembershipService.php
Labels: bug, Needs Review, Needs Tests

#957 UR 2826 Fix - Reflect updated plan type in change plan
  modules/membership/includes/AJAX.php
Labels: bug, Approved, Ready to Merge

#981 UR-2579 Feature - Site Assistent menu introduction.
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin.scss
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/deactivation-feedback-rtl.css
  assets/css/deactivation-feedback.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/menu.scss
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/settings-rtl.css
  assets/css/settings.css
  assets/css/user-registration-default-frontend-rtl.css
  assets/css/user-registration-default-frontend.css
  assets/css/user-registration-default-rtl.css
  assets/css/user-registration-default.css
  assets/css/user-registration-form-preview-rtl.css
  assets/css/user-registration-form-preview.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/js/admin/admin.js
  assets/js/admin/dashboard-widget.js
  includes/admin/class-ur-admin-dashboard.php
  includes/admin/class-ur-admin-menus.php
  includes/admin/functions-ur-admin.php
  includes/class-ur-ajax.php
  includes/class-ur-post-types.php
  includes/functions-ur-core.php
  modules/membership/includes/AJAX.php
  modules/membership/includes/Admin/Database/Database.php
  modules/membership/includes/Admin/Services/MembershipService.php
  src/dashboard/Constants/index.js
  src/dashboard/Router/Router.js
  src/dashboard/components/Header/Header.js
  src/dashboard/screens/Dashboard/Dashboard.js
  src/dashboard/screens/Dashboard/components/UsefulPlugins.js
  src/dashboard/screens/Help/Help.js
  src/dashboard/screens/SiteAssistant/SiteAssistant.js
  src/dashboard/screens/SiteAssistant/components/DefaultFormMissing.js
  src/dashboard/screens/SiteAssistant/components/DefaultWordPressLogin.js
  src/dashboard/screens/SiteAssistant/components/PaymentSetup.js
  src/dashboard/screens/SiteAssistant/components/RequiredPagesMissing.js
  src/dashboard/screens/SiteAssistant/components/SendTestEmail.js
  src/dashboard/screens/SiteAssistant/components/SpamProtection.js
  src/dashboard/screens/SiteAssistant/components/index.js
  src/dashboard/screens/index.js
Labels: Ready to Merge, Needs Documentation, Feature

#986 Fixed pdf form header empty issue.
  includes/admin/class-ur-admin-settings.php
Labels: bug, Approved, Ready to Merge

#976 UR-2851 Enhance - Separate saving mechanism for each recaptcha
  assets/js/admin/settings.js
  assets/js/frontend/user-registration-recaptcha.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-captcha.php
  includes/class-ur-ajax.php
  includes/class-ur-captcha-conflict-manager.php
  includes/class-ur-frontend-scripts.php
  includes/functions-ur-core.php
  modules/membership/includes/Admin/Services/Stripe/StripeService.php
  user-registration.php
Labels: enhancement, Approved, Ready to Merge
