Repository wpeverest/user-registration, pull requests merged in 2025-08, with the labels that each got.

#888 Fix - Translation issue in membership.
  modules/membership/includes/Templates/membership-registration-form.php
Labels: bug, Approved, Merged, Tested

#889 UR-2617/Fix - Fatal error while sending payment successful email without membership.
  includes/class-ur-smart-tags.php
Labels: bug, Approved, Merged, Tested

#902 Ur 2817 Fix - Theme style not overrridding the plugin design styles
  assets/css/user-registration-default-frontend.scss
  assets/css/user-registration-form-preview.scss
  assets/css/user-registration.scss
Labels: bug, Approved, Merged, Tested

#905 Ur 2577 design issue all fields smart tag
  assets/css/my-account-layout.scss
Labels: bug, Approved, Merged, Tested

#907 UR 2400 - Email notification to user on admin profile update.
  includes/class-ur-emailer.php
Labels: bug, Approved, Merged, Tested

#911 Ur 2845 Fix - Partial restriction on section of elementor
  modules/content-restriction/class-urcr-frontend.php
Labels: bug, Approved, Merged, Tested

#913 UR-2767 Email delivery failure notice threshold.
  includes/functions-ur-core.php
Labels: enhancement, Accessibility, Merged, Tested

#915 UR-2763 Tweak - Improve smart tags link label and design in email settings.
  assets/css/settings.scss
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-email.php
Labels: enhancement, Approved, Merged, Tested

#916 UR-2716 - Fix - Fixed design glitch in membership settings.
  assets/js/admin/settings.js
  modules/membership/includes/AJAX.php
  modules/membership/includes/Admin/Services/MembershipService.php
Labels: bug, Approved, Merged, Tested

#921 UR-2714 Enhance - Improve profile picture upload UX.
  assets/js/frontend/my-account.js
  templates/myaccount/form-edit-profile.php
Labels: enhancement, Approved, Merged, Tested

#926 UR-2717 Fix - Error message displayed while creating member.
  modules/membership/includes/Admin/Members/Members.php
Labels: bug, Approved, Merged, Tested

#927 UR-2896 Tweak - Display membership plan in profile detail for frontend listing
  includes/admin/class-ur-admin-profile.php
Labels: enhancement, Approved, Merged, Tested

#932 Fix membership field locked even when payment method is not enabled.
  assets/js/admin/form-builder.js
  assets/js/modules/membership/admin/membership-groups.js
Labels: bug, Approved, Merged, Tested

#934 UR-2904 Tweak - Sequence of upgrade and changelog in navigation bar
  src/dashboard/components/Header/Header.js
Labels: enhancement, Approved, Merged, Tested

#936 UR-2905 Tweak - Classname consistency for all buttons
  src/dashboard/screens/Dashboard/Dashboard.js
  src/welcome/components/App.js
Labels: enhancement, Approved, Merged, Tested

#948 UR-2934 Fix - Field Label translation in polylang
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#950 UR-2566 Fix - Frontend listing design issue for frontend and admin settings
  modules/membership/includes/Admin/Membership/Membership.php
Labels: bug, Approved, Merged

#931 UR-2822 Fix - Override global setting retain in page reload
  assets/js/modules/content-restriction/admin/urcr-custom.js
Labels: Approved, Ready to Merge, Tested

#933 UR 2787 enhance reduce users confusion around pro version
  assets/css/settings.scss
  assets/images/connect.gif
  assets/images/rocket.gif
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-menus.php
  includes/admin/class-ur-admin-settings.php
  includes/admin/settings/class-ur-settings-license.php
  includes/admin/views/html-admin-settings.php
  includes/class-ur-ajax.php
  includes/class-ur-plugin-updater.php
  includes/functions-ur-core.php
Labels: enhancement, Approved, Merged, Tested

#899 UR-2663 Dev - Filter to hide my account page selection notice
  includes/admin/notifications/class-ur-admin-notices.php
Labels: enhancement, Approved, Merged, Tested

#947 UR - 2923 Security - Updated sql prepare for members list table query.
  modules/membership/includes/Admin/Repositories/MembersRepository.php
Labels: Approved, Ready to Merge, Tested, Security

#942 UR 2788 - Fix - Ajax and Nonce related issues.
  assets/js/frontend/ur-login.js
  assets/js/frontend/user-registration.js
  includes/class-ur-ajax.php
  includes/class-ur-form-handler.php
  includes/class-ur-frontend-scripts.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
  templates/form-registration.php
Labels: bug, Approved, Merged, Tested

#903 Ur 2824 Fix - WooCommerce required fields validation not working
  assets/js/frontend/user-registration-form-validator.js
Labels: bug, Approved, Merged, Tested

#940 UR 2669 - Feature - Manual Payment renewal for membership.
  assets/css/modules/membership/user-registration-membership-frontend.scss
  assets/css/my-account-layout.scss
  assets/js/modules/membership/frontend/user-registration-membership-frontend.js
  includes/Functions/CoreFunctions.php
  includes/class-ur-cron.php
  includes/class-ur-smart-tags.php
  modules/membership/includes/AJAX.php
  modules/membership/includes/Admin/Repositories/MembersSubscriptionRepository.php
  modules/membership/includes/Admin/Services/EmailService.php
  modules/membership/includes/Admin/Services/OrderService.php
  modules/membership/includes/Admin/Services/Paypal/PaypalService.php
  modules/membership/includes/Admin/Services/Stripe/StripeService.php
  modules/membership/includes/Admin/Services/SubscriptionService.php
  modules/membership/includes/Admin/Settings/class-ur-settings-membership.php
  modules/membership/includes/Crons.php
  modules/membership/includes/Emails/EmailSettings.php
  modules/membership/includes/Emails/User/UR_Settings_Membership_Ended_User_Email.php
  modules/membership/includes/Emails/User/UR_Settings_Membership_Expiring_Soon_User_Email.php
  modules/membership/includes/Frontend/Frontend.php
  modules/membership/includes/Templates/Emails/payment-successful-email.php
  modules/payment-history/Admin/OrderService.php
  templates/myaccount/membership.php
  user-registration.php
Labels: Needs Review, Needs Tests, Needs Documentation, Feature

#945 UR 2719 - No option to reactivate membership after cancellation.
  assets/css/my-account-layout.scss
  assets/js/modules/membership/frontend/user-registration-membership-frontend.js
  includes/class-ur-user-approval.php
  includes/functions-ur-core.php
  modules/membership/includes/AJAX.php
  modules/membership/includes/Admin/Repositories/SubscriptionRepository.php
  modules/membership/includes/Admin/Services/Stripe/StripeService.php
  modules/membership/includes/Admin/Services/SubscriptionService.php
  modules/payment-history/Admin/OrderService.php
  templates/myaccount/membership.php
Labels: enhancement, Needs Review, Needs Tests

#951 UR-2914 Enhance - Registration form settings design
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/admin.scss
  assets/css/components/_bulkactions.scss
  assets/css/components/_dropdown.scss
  assets/css/components/_input.scss
  assets/css/components/_toggle.scss
  assets/css/modules/membership/user-registration-membership-admin.css
  assets/css/modules/membership/user-registration-membership-admin.scss
  assets/css/settings-rtl.css
  assets/css/settings.css
  assets/css/ur-notice-rtl.css
  assets/css/ur-notice.css
  assets/css/ur-notice.scss
  assets/css/user-registration-form-preview-rtl.css
  assets/css/user-registration-form-preview.css
  assets/js/admin/admin.js
  includes/admin/functions-ur-admin.php
  includes/functions-ur-core.php
  includes/functions-ur-template.php
Labels: enhancement, Approved, Merged, Tested
