Repository wpeverest/user-registration, pull requests merged in 2025-03, with the labels that each got.

#810 Fix - Conflict while using analytics for UR and EVF at a same time.
  includes/admin/class-ur-admin-assets.php
Labels: bug, Approved, Merged, Tested

#815 Fix - Issue while assigning my account page in settings.
  assets/js/admin/settings.js
Labels: bug, Needs Review, Needs Tests

#818 Fix- Row settings conditional logic not working on profile edit.
  templates/myaccount/form-edit-profile.php
Labels: bug, Approved, Needs Tests, Ready to Merge

#817 Fix - YITH multi vendor conflict.
  includes/class-ur-smart-tags.php
Labels: bug, Approved, Needs Tests, Ready to Merge

#812 Enhance - Compatibility of passwordless login and role based redirection.
  includes/functions-ur-core.php
Labels: enhancement, Approved, Needs Tests, Ready to Merge

#813 Fix - Validation on the disabling default WordPress page setting.
  assets/js/admin/settings.js
  includes/admin/class-ur-admin-menus.php
  includes/class-ur-ajax.php
Labels: bug, Needs Review, Needs Tests

#814 Enhancement - Displays the sucess message after confirming registration through email.
  assets/css/user-registration.scss
  assets/js/frontend/user-registration.js
  includes/class-ur-email-confirmation.php
Labels: enhancement, Approved, Needs Tests

#827 Fix - All field smart tag not working in admin verified email.
  includes/functions-ur-core.php
Labels: bug, Approved, Merged, Tested

#828 Fix - Lambda expression not supported in php version less than 7 4.
  includes/admin/class-ur-admin-export-users.php
Labels: bug, Approved, Merged, Tested

#830 UR 2264 Security - Vulnurability fix for auto_login after registration.
  includes/frontend/class-ur-frontend-form-handler.php
  modules/membership/includes/AJAX.php
  modules/membership/includes/Admin/Services/MembersService.php
  modules/membership/includes/Admin/Services/Paypal/PaypalService.php
  modules/membership/includes/Admin/Services/Stripe/StripeService.php
Labels: Approved, Ready to Merge, Tested, Security
