Repository wpeverest/user-registration, pull requests merged in 2025-04, with the labels that each got.

#800 UR-2013 - Tweak Logout endpoint translation issues
  includes/functions-ur-core.php
  includes/functions-ur-template.php
  templates/myaccount/navigation.php
Labels: bug, Approved, Needs Tests, Needs Documentation

#816 Feature - System Information
  assets/css/admin.scss
  assets/js/admin/admin.js
  includes/admin/class-ur-admin-status.php
  includes/admin/settings/class-ur-settings-misc.php
  includes/admin/views/html-admin-page-status-logs.php
  includes/admin/views/html-admin-page-status.php
  includes/admin/views/html-admin-page-system-info.php
  includes/class-ur-ajax.php
  includes/class-ur-emailer.php
  includes/class-ur-install.php
  includes/class-ur-logger.php
  includes/frontend/class-ur-frontend-form-handler.php
  includes/functions-ur-core.php
  includes/log-handlers/class-ur-log-handler-file.php
  uninstall.php
Labels: Status: Needs Docs, Approved, Needs Tests, Ready to Merge

#821 UR-1887 : Updated blacklist field for unplublished form
  .github/sync-file-list.yml
  .github/workflows/sync.yml
  assets/js/admin/enhanced-select-custom.js
  includes/admin/class-ur-admin-assets.php
  includes/admin/class-ur-admin-menus.php
  includes/functions-ur-core.php
Labels: bug, enhancement, Needs Review, Needs Tests

#819 UR-2135 : Enhanced realtime validation code
  assets/js/frontend/user-registration-form-validator.js
  templates/form-registration.php
Labels: enhancement, Needs Review, Needs Tests

#822 Fix - Check box smart tag not working for Email Verified - Awaiting Admin Approval Email.
  includes/class-ur-smart-tags.php
Labels: bug, Approved, Needs Tests, Ready to Merge

#820 Feature - Divi compatibility with all shortcodes
  .github/workflows/sync.yml
  assets/css/user-registration.scss
  assets/images/blocks/content-restriction.svg
  assets/images/blocks/edit-password.svg
  assets/images/blocks/edit-profile.svg
  assets/images/blocks/login-form.svg
  assets/images/blocks/membership-groups.svg
  assets/images/blocks/my-account.svg
  assets/images/blocks/registration-form.svg
  assets/images/blocks/thankyou.svg
  composer.json
  includes/3rd-party/DiviBuilder/Builder.php
  includes/3rd-party/DiviBuilder/BuilderAbstract.php
  includes/3rd-party/DiviBuilder/Modules/ContentRestriction.php
  includes/3rd-party/DiviBuilder/Modules/EditPassword.php
  includes/3rd-party/DiviBuilder/Modules/EditProfile.php
  includes/3rd-party/DiviBuilder/Modules/LoginForm.php
  includes/3rd-party/DiviBuilder/Modules/MembershipGroups.php
  includes/3rd-party/DiviBuilder/Modules/MembershipThankYou.php
  includes/3rd-party/DiviBuilder/Modules/MyAccount.php
  includes/3rd-party/DiviBuilder/Modules/RegistrationForm.php
  includes/Functions/CoreFunctions.php
  modules/content-restriction/class-urcr-shortcodes.php
  src/widgets/divi-builder/index.js
  src/widgets/divi-builder/modules/ContentRestriction.js
  src/widgets/divi-builder/modules/EditPassword.js
  src/widgets/divi-builder/modules/EditProfile.js
  src/widgets/divi-builder/modules/LoginForm.js
  src/widgets/divi-builder/modules/MembershipGroups.js
  src/widgets/divi-builder/modules/MembershipThankYou.js
  src/widgets/divi-builder/modules/MyAccount.js
  src/widgets/divi-builder/modules/RegistrationForm.js
  user-registration.php
  webpack.config.js
Labels: Approved, Needs Tests, Feature Request, Ready to Merge, Needs Documentation

#832 Ur 2144 conditional logic based on membership plans in membership field
  assets/js/modules/membership/admin/membership-groups.js
  modules/membership/includes/Admin/Forms/Views/admin-membership.php
  modules/membership/includes/Templates/membership-registration-form.php
Labels: enhancement, Approved, Ready to Merge

#833 Ur 2184 Fix - Blocks design rendering issue
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/deactivation-feedback-rtl.css
  assets/css/deactivation-feedback.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/settings-rtl.css
  assets/css/settings.css
  assets/css/ur-notice-rtl.css
  assets/css/ur-notice.css
  assets/css/user-registration-default-frontend-rtl.css
  assets/css/user-registration-default-frontend.css
  assets/css/user-registration-default-rtl.css
  assets/css/user-registration-default.css
  assets/css/user-registration-form-preview-rtl.css
  assets/css/user-registration-form-preview.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  includes/blocks/block-types/class-ur-block-registration-form.php
  includes/class-ur-preview.php
  includes/class-ur-shortcodes.php
  includes/functions-ur-page.php
  includes/functions-ur-template.php
  modules/content-restriction/admin/class-urcr-admin-meta-boxes.php
  modules/membership/includes/Admin.php
  modules/membership/includes/Frontend/Frontend.php
  modules/membership/includes/ShortCodes.php
Labels: bug, Needs Review

#829 UR 2265 Fix - Membership paypal payment issue
  modules/membership/includes/Admin/Services/EmailService.php
  modules/membership/includes/Admin/Services/OrderService.php
  modules/membership/includes/Admin/Services/Paypal/PaypalService.php
  modules/membership/includes/Admin/Services/SubscriptionService.php
  modules/membership/includes/Templates/Emails/payment-successful-email.php
Labels: bug, Needs Review, Needs Tests

#825 Dev - Added string for wpml translation.
  includes/functions-ur-core.php
  includes/validation/class-ur-form-validation.php
  wpml-config.xml
Labels: enhancement, Needs Review, Needs Tests

#836 UR-2277 Bug - Auto enable Payment history when enabling payment addons.
  assets/extensions-json/all-features.json
  includes/RestApi/controllers/version1/class-ur-modules.php
  package-lock.json
  package.json
  src/context/dashboardContext.js
  src/dashboard/screens/Modules/Modules.js
  src/dashboard/screens/Modules/components/ModuleItem.js
  webpack.config.js
Labels: bug, Approved, Needs Review, Needs Tests

#844 Ur-2324 Security - vulnerability fix reported by Wordfence.
  includes/class-ur-ajax.php
  includes/class-ur-preview.php
  includes/frontend/class-ur-frontend-form-handler.php
  modules/membership/includes/AJAX.php
Labels: Approved, Ready to Merge, Tested, Security

#842 UR-2339 : Updated regex for USA zip code validation
  includes/class-ur-smart-tags.php
Labels: bug, Needs Review, Needs Tests

#846 UR-2276 : Fixed shortcode issue in form listing page
  includes/admin/class-ur-admin-registrations-table-list.php
Labels: bug, Needs Review, Needs Tests

#845 Dev - Hook to modify lost passwords form placeholder.
  templates/myaccount/form-lost-password.php
Labels: enhancement, Approved, Merged, Tested

#838 UR-2281 Enhance - Scroll to top on category selection on form template page
  src/form-templates/components/Main.js
Labels: enhancement, Approved, Merged, Tested

#841 Remove - Duplicate icons for validation error message.
  assets/css/activation-rtl.css
  assets/css/activation.css
  assets/css/admin-rtl.css
  assets/css/admin.css
  assets/css/dashboard-rtl.css
  assets/css/dashboard.css
  assets/css/deactivation-feedback-rtl.css
  assets/css/deactivation-feedback.css
  assets/css/menu-rtl.css
  assets/css/menu.css
  assets/css/metabox-rtl.css
  assets/css/metabox.css
  assets/css/my-account-layout-rtl.css
  assets/css/my-account-layout.css
  assets/css/settings-rtl.css
  assets/css/settings.css
  assets/css/ur-notice-rtl.css
  assets/css/ur-notice.css
  assets/css/user-registration-default-frontend-rtl.css
  assets/css/user-registration-default-frontend.css
  assets/css/user-registration-default-rtl.css
  assets/css/user-registration-default.css
  assets/css/user-registration-form-preview-rtl.css
  assets/css/user-registration-form-preview.css
  assets/css/user-registration-rtl.css
  assets/css/user-registration-setup-wizard-rtl.css
  assets/css/user-registration-setup-wizard.css
  assets/css/user-registration-smallscreen-rtl.css
  assets/css/user-registration-smallscreen.css
  assets/css/user-registration.css
  assets/css/user-registration.scss
  templates/notices/error.php
Labels: bug, Approved, Merged, Tested

#834 Fix - Registration Form validation for elementor popup.
  assets/js/frontend/user-registration.js
Labels: bug, Approved, Merged, Tested
